### ISSUE TITLE
can't see trezor testnet account(m/44/1/0/0) in geth

### ISSUE THREAD

**Issue by leochan007** [trezor/trezor-core#101]
when using "personal.listWallets" in geth console,
only can see the FIRST mainet account (m/44/60/0/0)  , actually there is  plenty of  account in m/44/60/0/0  and m/44/1/0/0. 

and can't open wallet with URL shown for account 1.

OS: mac os.

**Comment by prusnak** [comment]
Geth issue tracker is here: https://github.com/ethereum/go-ethereum
