### ISSUE TITLE
ui: on-screen qr code display truncated on "confirm address" screen

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#107]
when running a command like:
`python2 trezorctl get_address -c Bitcoin -n "Bitcoin/0'/0/0" -d`
the top of the qr code on the "Confirm address" screen is truncated/obscured by the bottom of the address string. This does seem to affect scanability as when I stopped displaying the address text in `/trezor-core/src/apps/wallet/get_address.py` the code began scanning quickly/easily.

**Comment by mcudev** [comment]
Even more for : `python2 trezorctl get_address -c Bitcoin -n "Bitcoin/0'/0/0" -t segwit -d`

**Comment by prusnak** [comment]
Yes, this will be addressed before the release.

**Comment by jpochyla** [comment]
Fixed in https://github.com/trezor/trezor-core/commit/c34ee98731b25e1f60b999a7a1369b483a6a564b

**Comment by mcudev** [comment]
Nice!
It works. QR codes are scannable. My feedback is to consider optimizing later for `-t segwit`.
From https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
"For presentation, lowercase is usually preferable, but inside QR codes uppercase SHOULD be used, as those permit the use of alphanumeric mode, which is 45% more compact than the normal byte mode."

**Comment by prusnak** [comment]
Segwit optimization for QR code added in d8ac07e4554cf93d3211a80015ba40b21774c9f0

**Comment by mcudev** [comment]
that works, thanks! i need a better tool to verify that the correct mode (alphanumeric) is used. my scanner just shows "text" for both the before and after qr codes. it's probably doing the right thing based on what i see in `EncodeSourceData`, but i'd like to be sure.

**Comment by mcudev** [comment]
I was able to verify that the QR code generated now uses the alphanumeric mode (instead of byte mode). I accomplished this in the most time consuming way possible. I built a zxing barcode scanner app for android and watched it in the debugger.

**Comment by prusnak** [comment]
Wow, that is what I call dedication!!!
