### ISSUE TITLE
firmware: recovery_device

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#114]
I noticed while entering my mnemonic for the `recovery_device` flow that if my thumb accidentally tapped the word twice (to accept it) that the extra tap was slow enough that it happened on the "Type #. word" label/prompt and that actually accepted the extra tap as a blank word. This results in an invalid mnemonic. I was expecting that the text label was not interactive.

**Comment by jpochyla** [comment]
Good catch, thanks!

**Comment by jpochyla** [comment]
Fixed in https://github.com/trezor/trezor-core/commit/fcd712a0b058b5a67718ed1f0de99d8bcdd6f8b1

**Comment by mcudev** [comment]
tested, good, thanks!
