### ISSUE TITLE
firmware: recovery_device dry run not implemented

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#115]
`python2 trezorctl recovery_device -d`
appears to have the same effect on the device as
`python2 trezorctl recovery_device`

I was also wondering if it would be useful to make the mnemonic display after input by using the 6 screens of 4 approach (or however many screens based on the recovery mnemonic word count). I guess it's not important because of the mnemonic sentence checksum, but it might assure users more that what they thought they input is what was accepted.

**Comment by jpochyla** [comment]
`dry_run` implemented in https://github.com/trezor/trezor-core/commit/fcd712a0b058b5a67718ed1f0de99d8bcdd6f8b1

**Comment by mcudev** [comment]
tested, good, thanks!

btw, i did notice that while testing the non-dry run, the mnemonic loaded into the device and i could use things like normal. then i unplugged the device and replugged it and got "Device is not initialized". i did not look at why. that could be another bug if not intentional right now.

**Comment by mcudev** [comment]
all good. the subsequent storage wipe was due to my config of `PYOPT`.
