### ISSUE TITLE
ButtonAck returns unknown message during device tests

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-core#118]
During device tests, sending the `DebugLinkDecision` seems to cause the tests to fail due to `ButtonAck` being sent directly after.

Cannot be worked around without refactoring `python-trezor`. Essential for security review and fuzzing.

**Comment by jpochyla** [comment]
Should be fixed now [by UDP debuglink fix in python-trezor](https://github.com/trezor/python-trezor/commit/0ca58f99e5447ec3187f6803baeacaf07690535d) and [by preventing unloading of debug signals](https://github.com/trezor/trezor-core/commit/b5e142307b5698f666796e3628d1a97ad48d3f81).
