### ISSUE TITLE
update startup code

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#12]
to erase all RAM similarly to reset_handler here: https://github.com/trezor/trezor-mcu/blob/master/startup.s

**Comment by mcudev** [comment]
Looks like you might have to add a call to `SystemInit` right before `main` and do all the vector table stuff.
This also depends on the linker script, so probably changes there too.
Do you intend to try to push this upstream to micropython, or just keep it as a patch in https://github.com/trezor/micropython, or something else?

**Comment by prusnak** [comment]
We'll see in the end if it makes sense to upstream that or not. In general we want to upstream most of the stuff, to keep our patchset small.

**Comment by mcudev** [comment]
Makes sense. I've got some work on this. Kind of at the "trying things" stage. The hardest part so far has been reconciling how to deal with all the different sections (due to -fdata-sections -ffunction-sections). There is so much linker input that ends up getting garbage collected (hundreds of sections). I'm trying various approaches to see what ends up clean.

**Comment by mcudev** [comment]
@prusnak I've got a start on this at https://github.com/mcudev/trezor-core/tree/boardloader-update

I've got some more ideas on how to improve it. This is a good start to look at though to see if you like the general direction.

**Comment by prusnak** [comment]
startup code for boardloader was updated via https://github.com/trezor/trezor-core/pull/18

left to do is bootloader and firmware

keeping this open for tracking purposes

**Comment by mcudev** [comment]
Related code review item:
The `jump_to` re-points the exception handlers before the C code that comprises them have been given a good environment to run (that's one of the main purposes of the `reset_handler` that runs after the `jump_to`). So, the `jump_to` probably needs to disable interrupts before the VTOR switch and then the `reset_handler`s need to re-enable interrupts.

For example, the boardloader has three non-default exception handlers configured: PendSV (vector table offset=0x38), SysTick (0x3c), and SDIO (0x104). The SysTick  is definitely configured (by the HAL) and taking interrupts when the code stages are switched.

**Comment by mcudev** [comment]
I was wondering, "What is the point of having a reset_handler for each later stage?". Below is what I came up with. Am I missing anything important?:

 * to setup .data and .bss for the new stage's c code
 * give the new stage of code a fresh/clean/empty stack (but registers etc... are not reset as is done during system reset) (but it could do this itself anyways)
 * give the new stage of code the ability to replace exception handlers (interrupt vectors) (but it could do this itself anyways)
 * makes it easier to flash just one part for development, like firmware0 (but there is no guarantee that the environment is setup the same as if all stages had run)

**Comment by prusnak** [comment]
Closing, thank you very much!
