### ISSUE TITLE
Initialize never works, when device waits for user confirmation

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#126]
Easy to reproduce:

* go to wallet
* click on "eye" (or sign tx, or sign a transaction, or anything that requires user interaction)
* reload wallet

Initialize never gets an answer, so the device is never read correctly and requires reconnecting

**Comment by karel-3d** [comment]
Also, what might be related and what produces `malformed wire format` with bridge and `Illegal offset` with webUSB - so probably protobuf

* go to wallet
* click on "eye" (or sign tx, or sign a transaction, or anything that requires user interaction)
* reload wallet
* click QR on the device

Wallet then gets some strange reply to the Initialize, which is not even wrong message but an invalid protobuf.

**Comment by karel-3d** [comment]
When I looked "lower" into what happens in the second case, after pressing QR button when waiting for the Initialize:

* PC sends message Initialize to trezor
* nothing happens
* user presses QR code
* device returns ButtonRequest with code ButtonRequest_Address
* wallet automatically returns ButtonAck
* trezor immediately returns features, correctly
* wallet then sends Initialize again to trezor
* trezor sends empty result (0 bytes). This confuses wallet (or bridge, repectively).

**Comment by prusnak** [comment]
Fixed by https://github.com/trezor/trezor-core/commit/8f1ed5edcecb3f177809cfdcc77802e15b65fc63
