### ISSUE TITLE
Adding state to passphraseAck always throws mismatch

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#128]
This is my workflow, which always produces mismatch.

* I call device with Initialize
* I get features with a state `A` in return. I never call any passphrase yet, user never enters any passphrase. Yet I save a state `A` to the device mode.
* I then call getPublicKey.
* I get ButtonRequest in return.
* To the ButtonRequest, I reply ButtonAck. User select "on host" (on_device false)
* I get PassphraseRequest again
* To that passphrase request, I - for the first time - reply with a passphrase, and add the state `A`, because that is saved with the device.
* To that, I get a passphrase mismatch.

Where is a step I am doing wrong?

I understand that `A` is not a hash of the passphrase - since I never enter passphrase and I still get `A` (so it cannot be derived from the passphrase). But I also don't understand what am I doing wrong.

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-core/commit/df10f5df3fced066733ab28a45ae9a159a16e688
