### ISSUE TITLE
Deleting first letter of passphrase on device does not delete the letter in UI

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#131]
When I delete the first letter, it is not actually deleted in the GUI. (However, after writing another letter, it overwrites the existing letter.)

I am not sure which passphrase is actually sent, if empty or the stuck letter.

See screenshot from emulator; the same issue is on device. First is correct state with a letter, second is a wrong state with letter removed

![screenshot from 2018-03-01 03-58-38](https://user-images.githubusercontent.com/104945/36824956-440567f2-1d05-11e8-91d9-c8e1ad1c9ebc.png)

![screenshot from 2018-03-01 03-58-44](https://user-images.githubusercontent.com/104945/36824958-44234d62-1d05-11e8-99b1-76dcd148596a.png)

**Comment by jpochyla** [comment]
Fixed in f74cbead5e1ca3fe6ff3203e63504cfff5dbd44a
