### ISSUE TITLE
Screen still show "trezor.io/start" after reset

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#132]
After reset with delayed setup (as on the new wallet), device still shows "Go to trezor.io/start", as seen on the screenshot.

It does not happen on the old wallet with the non-delayed setup, see second screenshot

It can be reproduced on both device and emulator.

![screenshot from 2018-03-01 04-06-52](https://user-images.githubusercontent.com/104945/36825219-9f0c26d0-1d06-11e8-9c52-25165d45bdad.png)

![screenshot from 2018-03-01 04-09-57](https://user-images.githubusercontent.com/104945/36825222-a67a2d36-1d06-11e8-8cbe-4ba3ca410a20.png)

**Comment by karel-3d** [comment]
Once the screen orientation is changed by swiping, the text is correct, even when changed back.

**Comment by prusnak** [comment]
Fixed in 144e2013bdeeab7f029e97801006c27c55b18b7c
