### ISSUE TITLE
needs_backup flag is set to false prematurely

### ISSUE THREAD

**Issue by michal-novacek** [trezor/trezor-core#137]
If a backup is initiated by sending `backup_device` message to the device, the device displays the "Backup your seed" screen with an "I understand" (hold to confirm) button.

![image](https://user-images.githubusercontent.com/5519597/36905774-76d09bd6-1e34-11e8-924e-21bd60e3a729.png)

However, the `needs_backup: false` flag is already set as soon as the `backup_device` call is received. If the user doesn't touch and hold "I understand" and disconnects the device instead, it will no longer display the NEEDS BACKUP warning on the display or send the `needs_backup: true` flag in features.

Please only set the `needs_backup: false` flag after user completes this screen..

**Comment by prusnak** [comment]
Fixed by https://github.com/trezor/trezor-core/pull/138
