### ISSUE TITLE
Extend needs_backup flag with backup_done flag

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#145]
Which will be set at the end of the backup process. This will be used to detect broken backup process (i.e. it started, but was not finished).

Another option is to change it from bool (`b''` / `b'\x01'`) to int (`b''` / `b'\x01'` / `b'\x02'`)

**Comment by michal-novacek** [comment]
another flag is better for backwards compatibility

**Comment by jhoenicke** [comment]
How about a counter, so that you can show something like "WARNING there have been n backup attempts  before. Someone else may have seen the backup words."

**Comment by prusnak** [comment]
Added new flag `unfinished_backup` into `Features` and storage.

Implemented in b83ffee3af8a3e2735dd285db1379204aeafd779
