### ISSUE TITLE
Bitcoin Gold. Failed to send transaction Error details: Transaction has changed during signing

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-core#147]
I am trying to send Bitcoin Gold from my Trezor Model T wallet, but I get the following error:

"Failed to send transaction
Error details: Transaction has changed during signing"

This error appears on the browser window when I confirm the transaction on the Trezor.

Technical details: Chromium on Linux
beta-wallet.trezor.io

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-core/pull/151
