### ISSUE TITLE
Ethereum TX Formatting problem

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-core#154]
This only happens when sending <1ETH

so 0.21 ĺooks suboptimal like this:

![trezor_t_eth_tx](https://user-images.githubusercontent.com/111600/37179276-64b52f66-2325-11e8-9a10-f6a72d98253f.jpg)

and 1.21 looks better like this:
![20180308_230934](https://user-images.githubusercontent.com/111600/37179477-0cb2aefa-2326-11e8-854a-a6122a7e711e.jpg)

**Comment by prusnak** [comment]
Already fixed in https://github.com/trezor/trezor-core/commit/c7c5f55508076d541e523a2d46007c453d91ac75

Will be released in the next firmware update.
