### ISSUE TITLE
Consolidate Messages For Different Coin Types

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-core#161]
Currently, there are three main coin types: Bitcoin, Ethereum, and NEM. The inner workings of these coins are all different. They use different cryptography and so on. But, the public interface of the messages are almost identical. I may be wrong, but my guess is that the public interface for these messages could be merged together so that it's not necessary for developers to bifurcate the code in their apps.

Here is an example of my code in C#. I have been able to put a layer over the top of Bitcoin and Ethereum, but I'm struggling with NEM because I can't get Nanowallet to work, and have no reference point for generated addresses for NEM.

```
        public async Task<string> GetAddressAsync(string coinShortcut, uint coinNumber, bool isChange, uint index, bool showDisplay, AddressType addressType)
        {
            try
            {
                System.Diagnostics.Debug.WriteLine($"Attempting to get address for {coinShortcut} at Index: {index}, IsChange: {isChange}");

                //ETH and ETC don't appear here so we have to hard code these not to be segwit
                var coinType = Features.Coins.FirstOrDefault(c => c.CoinShortcut.ToLower() == coinShortcut.ToLower());

                var isSegwit = coinType != null && coinType.Segwit;

                var path = GetAddressPath(isSegwit, isChange, index, coinNumber);

                switch (addressType)
                {
                    case AddressType.Bitcoin:

                        return (await SendMessage<Address, GetAddress>(new GetAddress { ShowDisplay = showDisplay, AddressNs = path, CoinName = GetCoinType(coinShortcut)?.CoinName, ScriptType = isSegwit ? InputScriptType.Spendp2shwitness : InputScriptType.Spendaddress })).address;

                    case AddressType.Ethereum:

                        var ethereumAddress = await SendMessage<EthereumAddress, EthereumGetAddress>(new EthereumGetAddress { ShowDisplay = showDisplay, AddressNs = path });

                        var sb = new StringBuilder();
                        foreach (var b in ethereumAddress.Address)
                        {
                            sb.Append(b.ToString("X2").ToLower());
                        }

                        var hexString = sb.ToString();

                        return $"0X{hexString}";

                    case AddressType.NEM:
                        throw new NotImplementedException();
                    default:
                        throw new NotImplementedException();
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.ToString());
                throw;
            }
        }
```

My app requires that I simply send a request and get back a string address. This method neatly does this so my app doesn't have to care about the coin type. It would be nice if there were a Trezor message that behaved like this. If it's not possible, then no problem.

**Comment by prusnak** [comment]
While I agree there might be a way how to design a common interface for getting addresses/accounts, I don't think this is possible for transaction signing. So, in the end, you will end up bifurcating your code base.

I will close that for the time being as there is no plan to implement an interface like this, but we are thinking about the options how not to end up with adding hundreds of new messages for each new coin.

**Comment by MelbourneDeveloper** [comment]
Thanks. Yes, that was my point. There are new coin types being added all the time. My worry is that every new coin type is going to have messages for getting addresses and signing etc. 

Actually, is there are a set of guidelines for new coins to follow in order to minimize all the bifurcation? 

WAVES looks like it's going to need more bifurcation so a set of guidelines about the pull request would really help in future.
