### ISSUE TITLE
Display rotation in lock screen & make it persistent

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-core#162]
Observations:
a) People sometimes thinks that display rotation is a software bug.
b) Lock screen and PIN entry is not affected by the rotation settings, which defeats its purpose for heads-down mounts.
c) Settings currently doesn't survive device restart.

Solution:
1) Make it as a device settings over ApplySettings() message as unprotected value (similar to background image & label).
2) Make PIN entry and lock screen compatible with rotation.
3) Disable rotation over swipe gesture.

**Comment by tsusanka** [comment]
Let's discuss this issue again, as mentioned on standup. I'm voting for disabling the rotation whatsoever (option 3), but I'm fine with option 1 as well.

**Comment by prusnak** [comment]
I would go for option 1.

**Comment by tsusanka** [comment]
@prusnak what is the default for option 1? If the default is OFF, then I agree

**Comment by prusnak** [comment]
Default would be NORTH = 0 degrees. Other options would be SOUTH = 180 degrees, WEST = 270 degrees, EAST = 90 degrees.

**Comment by tsusanka** [comment]
> Default would be NORTH = 0 degrees. Other options would be SOUTH = 180 degrees, WEST = 270 degrees, EAST = 90 degrees.

Uff, sorry, I've misunderstood. Ok, so you mean this but removing the option to change the setting using a swipe gesture, am I right?

**Comment by prusnak** [comment]
Yes, remove the gesture completely. Make it only settable via the ApplySettings message.

**Comment by TomBPotochek** [comment]
I like option 2, because I use it upright when on my desktop machine and then flipped 180° when I use it  on my phone with a short cable. I guess this option would make more sense if an adapter kind of like ![this](https://user-images.githubusercontent.com/43979399/55124244-59bf8500-50e4-11e9-8a93-c336b8417910.png) existed.

**Comment by tsusanka** [comment]
Merged via bd812fe

**Comment by tsusanka** [comment]
Btw the rotation obviously does not concern the bootloader, so if there is a bootloader splash screen, it is still rotated incorrectly. I think that's acceptable.

**Comment by tsusanka** [comment]
Test cases:
- Swiping does not rotate the screen.
- You can change the rotation using trezorctl (`trezorctl set_display_rotation east`)
- This setting stays after un/plug.
