### ISSUE TITLE
TREZOR T is displayed twice on Windows 10 in libusb listing, with the same path

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#165]
TREZOR T is displayed twice on Windows in libusb listing, with the same path. One of the listed devices then don't work (sometimes first and sometimes second, it seems random).

This behaviour doesn't happen in TREZOR Model One with the WebUSB enabled (from master).

This is observable in python-trezor, or in TREZOR Bridge that uses libusb. TREZOR Bridge currently fails in around 50% of cases because of this.

It is fixable in TREZOR Bridge (https://github.com/trezor/trezord-go/pull/28), but it should be fixed here.

I have made a simple GUI tool in go, that displays the number of TREZOR devices that libusb lists. This tool should work on GNU/Linux and macOS, but there is no reason for that currently.

```go
package main

import (
	"strconv"
	"time"

	"github.com/andlabs/ui"
	"github.com/trezor/trezord-go/usb"
)

func main() {
	check(ui.Main(func() {

		status := ui.NewLabel("0")
		box := ui.NewVerticalBox()

		box.Append(status, false)
		window := ui.NewWindow("Trezor Detect", 50, 50, false)
		window.SetMargined(true)
		window.SetChild(box)

		window.OnClosing(func(*ui.Window) bool {
			ui.Quit()
			return true
		})
		window.Show()

		w, err := usb.InitWebUSB()
		check(err)
		go func() {
			for {
				devs, err := w.Enumerate()
				check(err)

				status.SetText(strconv.Itoa(len(devs)))
				time.Sleep(500 * time.Millisecond)
			}
		}()

	}))

}

func check(e error) {
	if e != nil {
		panic(e)
	}
}
```

This correctly displays 1 in TREZOR T bootloader and TREZOR Model One with WebUSB enabled. It displays 2 with TREZOR T regular firmware.

(Note that the tool starts showing 1 with the linked trezord-go PR)

**Comment by karel-3d** [comment]
(in order to run the script on windows, you need to install golang, git and gcc)

**Comment by karel-3d** [comment]
This is binary of the GUI script, if you don't want to go through the pain of setting golang + git + gcc on windows

[bridgebug.zip](https://github.com/trezor/trezor-core/files/1800755/bridgebug.zip)

**Comment by karel-3d** [comment]
Some users after several wipes/resets apparently start seeing this correctly, with just one device. Which makes this bug still non-deterministic and not easily debuggable.

**Comment by karel-3d** [comment]
From my experimentation, Chrome with WebUSB turned on is similarly non-deterministic, sometimes the device is seen correctly, sometimes it's not. (Again only with TREZOR T)

**Comment by mocmocamoc** [comment]
See https://github.com/trezor/python-trezor/issues/223
The problem doesn't seem to happen with libusb 1.0.22-rc3 so it appears to be a libusb bug.

**Comment by slush0** [comment]
Workaround implemented in https://github.com/trezor/trezord-go/pull/28

**Comment by slush0** [comment]
This clearly describes the problem we've been facing: https://github.com/libusb/libusb/commit/71a779d078be83cae91fb2aa972d1069daec38d4#diff-eaebe812fd3cec44f65977933b49ec6a

Also, trezord seems to work well with libusb rc3, but we need to test it for all platforms first. Implemented workaround is a quick fix which shouldn't have any side effects.

**Comment by karel-3d** [comment]
I am closing this issue here because it is not trezor-core issue
