### ISSUE TITLE
Problem running the emulator

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-core#173]
make build_unix works fine - make emu fails for me. 
happening on ubuntu 18.04 after fresh reboot ( regarding the hint "This is normally a bug in some application using the D-Bus library.")
Please let me know if you need more information

```
ligi@li7 ~/g/3/trezor-core> make emu
./emu.sh
dbus[31948]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
./emu.sh: line 15: 31948 Aborted                 (core dumped) ../$EXE $ARGS $* $MAIN
Makefile:64: recipe for target 'emu' failed
```

**Comment by prusnak** [comment]
Not sure what is causing the issue, but the following workaround works:

`export DBUS_FATAL_WARNINGS=0` before running the emulator.

Pro-tip: you can even add this line to `emu.config` as this is being sourced from emu.sh

**Comment by ligi** [comment]
thanks for the very fast answer - emu is working now - YAY - thanks.
Feel free to close the issue - or perhaps leave it open for others that run into the same thing.

**Comment by prusnak** [comment]
For reference: what is the SDL2 version you have in your system?

**Comment by ligi** [comment]
```
⋊> ~ sdl2-config  --version 
2.0.8
```

**Comment by prusnak** [comment]
Hm, same version here (on openSUSE), but stuff works. I remember it was not working earlier for me. Most probably a distribution thing (DBUS vs SDL2 clash).

I also read that `unset XMODIFIERS` helps.

**Comment by prusnak** [comment]
For dbus problem, the solution is posted above.

For enabling the emu in Chrome extension, read the readme here:
https://github.com/trezor/trezor-chrome-extension

**Comment by lakshmisatya** [comment]
Hi prusnak,
I have tried export DBUS_FATAL_WARNINGS=0 and unset XMODIFIERS both. the error message was still being shown up. 
I am using ubunt 14. SDL version 2.0.8. 
BTW now I able to detect emulator with window.setUdp in chrome extension. But on trezor.io/start website my emu is not getting detected still. 
Where could be the issue? I have attached chrome extension screeshot for your reference. 

Regards
Lakshmi

![screenshot from 2018-05-03 10-14-49](https://user-images.githubusercontent.com/37800901/39561927-74a76f52-4ec6-11e8-89ee-6279d3de3375.png)

**Comment by prusnak** [comment]
If you still see the error message, the emulator has not started, that's why you don't see it in the website. You have added the ports using setUdp method correctly. Please post the terminal output, so we can see you run the following correctly:

```
export DBUS_FATAL_WARNINGS=0
unset XMODIFIERS
./emu.sh
```

**Comment by lakshmisatya** [comment]
Hi prusnak, Please find attached screen shot. Now we reinstalled all the stuff including ubuntu. 
D-bus error is not being shown, but still, the issue persists. Emu not getting connected to chrome extension. 

![screenshot from 2018-05-07 12-39-43](https://user-images.githubusercontent.com/37800901/39689491-973ae612-51f4-11e8-81da-ff7dae7a03e0.png)

**Comment by prusnak** [comment]
Use the Chrome Extension (window.setUdp) trick again.
