### ISSUE TITLE
Initialize didn't respond

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#175]
Steps to reproduce (chrome + macos):

1. Connect T2 (optionally unlock pin)
2. Go to beta-wallet (and let the wallet read accounts for first time)
3. Refresh wallet with console opened
4. When device is in initialize process (wallet send Initialize to device) refresh again (you need to be quick enough and do it before Initialize response from transport)
5. After wallet reloads device will be in unacquired state, and [trezor.js] [call] Sending Initialize {} will never be resolved.
6. Another refresh and device will start sending responses in messed up order:

[trezor.js] [device list] Configuring transports
[trezor.js] [device list] Configuring transports done
[trezor.js] [device list] Creating Device Object undefined
[trezor.js] [call] Sending Initialize Object
[trezor.js] [call] Received Features Object
[trezor.js] [session] releasing
[DeviceUpdate] action:
[DeviceUpdate] progress: initial
[trezor.js] [call] Sending Initialize Object
[trezor.js] [call] Received Features Object
**[trezor.js] [call] Sending GetPublicKey Object
[trezor.js] [call] Received Features Object**
[trezor.js] [session] releasing

**Comment by prusnak** [comment]
@jpochyla This has already been fixed, right? If yes, please close.

**Comment by jpochyla** [comment]
I will test it with removed coin defs.

**Comment by prusnak** [comment]
I think this is fixed now.
