### ISSUE TITLE
Trezor_core  emulator swipe doesn't work

### ISSUE THREAD

**Issue by lakshmisatya** [trezor/trezor-core#187]
Hi all,

When I try to use back up function from chrome, my trezor_core emulator showing first 4 words of seed. Then if I try to swipe, screen not responding. Is it the known bug? Please help me. 

Regards
Lakshmikanth

**Comment by prusnak** [comment]
Swipe works for me in the emulator.

Try swiping again and make a longer swipe.

**Comment by prusnak** [comment]
Master works for me
