### ISSUE TITLE
usb_start function not initiating properly

### ISSUE THREAD

**Issue by Vitalynx** [trezor/trezor-core#194]
When running the emulator I get this fatal error. (Running on unix build)
FATAL ERROR:
expr: sectrue * (0 == bind(usb_ifaces[i].sock, (struct sockaddr*)&usb_ifaces[i].si_me, sizeof(struct sockaddr_in)))
file: embed/unix/usb.c:96
func: usb_start
rev : 074e7c1-dirty
SHUTDOWN

**Comment by prusnak** [comment]
You run the emulator twice. The second instance could not start. Make
sure you only run the emulator once.
