### ISSUE TITLE
T2: Invalid amount and token name while sending Erc20 tokens 

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#198]
signing erc20 transaction will display amount of tokens in Wei as "eth" instead of "token_name"

**Comment by tsusanka** [comment]
Should be fixed now. When unknown token is sent to Trezor, it will display "unknown token value", identical to Trezor One.

Also for reference: some token amounts are written in Wei [token_name]. Although different than T1 this seems to be a feature, see the discussion [here](https://github.com/trezor/trezor-core/commit/19bae93d929424e28f8e5f2f914d7e3903036560#r28926249).
