### ISSUE TITLE
Research and add WebUSB support

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-core#2]
WebUSB is a new standard that will probably be implemented in Chrome and Firefox soon-ish (it is already in newest builds of Chrome in experimental mode).

It would be nice to support it right "off the bat". But I am not sure how hard would that be.

**Comment by spudowiar** [comment]
For reference, https://wicg.github.io/webusb/, and from a quick read of that, it doesn't look too hard to implement. Should be able to just add support for binary object storage (see that link) and then add the descriptors it needs (again, see that link)

**Comment by prusnak** [comment]
Implementation https://github.com/devanlai/dapboot/commit/7c6e6a70c39def7654f6c324a3d4ce4400432fca

Needs upstreaming USB BOS feature from devanlai/libopencm3 first.

**Comment by runn1ng** [comment]
Great find.

But devanlai/libopencm3 is behind libopencm3 master...?

**Comment by prusnak** [comment]
Does not matter. Moreover, I was pointed to source which does not
require patching libopencm3:
https://github.com/devanlai/dap42/blob/winusb-wip/src/USB/composite_usb_conf.c#L499

**Comment by runn1ng** [comment]
in the end we solved it in trezor-mcu ( https://github.com/trezor/trezor-mcu/commits/webusb , https://github.com/trezor/trezor-mcu/commits/webusb_fixed ) so I am closing this for now
