### ISSUE TITLE
Add zcash v3 txs (ZIP 202)

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#203]
See https://github.com/zcash/zips/blob/master/zip-0202.rst

I am not sure if it is better to be able to create both v1 and v3 transactions, for smoother transition, or just create v3 transactions, for simpler code.

v1 and v2 transactions are valid pre-fork, v3 are valid post-fork.

See also
* https://z.cash/upgrade/overwinter.html
* https://github.com/zcash/zips/issues/151

**Comment by daira** [comment]
I suspect it would be preferable for users to be able to upgrade before the fork, and have things Just Work through the fork, which requires being able to create both v1 and v3 transactions.

**Comment by prusnak** [comment]
@daira I was able to create and sign the transaction. It's raw form is:

`030000807082c40301dc754d63eff4698ee321476872519c53f14cfe58c9425c7ee464c206461ef5aa010000006a473044022039e3814541d8b9fcd09a43e9320514a327c79ce9473f679857afaee12ec7ba3d02207b00fad860dba848f280674129b347c7ffebeede8c85cf742ed854b0347af3600121030e669acac1f280d1ddf441cd2ba5e97417bf2689e4bbec86df4f831bf9f7ffd0ffffffff016c9be111000000001976a9145b157a678a10021243307e4bb58f36375aa80e1088ac0000000000000000`

But I am getting `TX decode failed. Code:-22`

Can you advise?

**Comment by prusnak** [comment]
I ommited v2 fields from tx. Is this correct?

**Comment by prusnak** [comment]
Relevant commits are https://github.com/trezor/trezor-core/commit/dfd02821af7a10bad5a4116f39f468133c2816ba and https://github.com/trezor/trezor-core/commit/cfa73b276e83746f69bfaac6d9c603d4665caf0a

**Comment by daira** [comment]
I'm not sure why you're getting this particular error, but I did see several discrepancies between the code in ``Bip143.preimage_hash`` after cfa73b2, and the specification of the transaction digest algorithm in [ZIP 143](https://github.com/zcash/zips/blob/master/zip-0143.rst#specification): in the latter,
* the input-specific fields (``outpoint``, ``scriptCode``, ``value``, ``nSequence``), when present, have been moved to the end of the digest input after the sighash type (# 10 in the list of input elements);
* ``nJoinSplit`` is not serialized. Instead, ``hashJoinSplits`` is serialized just after ``hashOutputs``. This will be 32 zero bytes if you don't have any JoinSplits.

Note that the input-specific fields are only present when serializing for an input, i.e. not when serializing for a JoinSplit signature (or for a binding or spend auth signature when you implement Sapling). But this shouldn't affect you if you don't support shielded transactions yet.

**Comment by prusnak** [comment]
Ah, thanks! I did not realise you forked BIP143 too. Will work on the changes.

**Comment by prusnak** [comment]
@daira I am closer to working solution, but there is still something missing. 

Adding an example (simple tx, no coinjoins, showing partial results such as ) would be very helpful: https://github.com/zcash/zips/blob/master/zip-0143.rst#example

**Comment by daira** [comment]
a5952d16db9e4841322e4c83b960e7b883f4c953 seems to be along the right lines. I'll see about writing an example. Ping @str4d

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-core/commit/8e9ae534c0d5633d36735910a6c2a1420d1457cf
