### ISSUE TITLE
How to trigger the hardware seed backup?

### ISSUE THREAD

**Issue by wuyu12138** [trezor/trezor-core#209]
Hello, I have found the protob messages in it, and there are many things about instruction in this file, also saw in the popup and popup - dist some corresponding methods, but I don't know how to use. I want to ask what should trigger the hardware on the web end the seeds of backup function?Or am I wrong?So how do you trigger a hardware seed backup?

**Comment by prusnak** [comment]
You send a `BackupDevice` message. This works only once for security purposes.

**Comment by wuyu12138** [comment]
Yes, I wrote a feedback on the hardware, when I send the BackupDevice, displays the type of equipment: 34, the corresponding instruction is BackupDevice information. But there is no trigger seed backup hardware and equipment function. I lack some steps?

**Comment by wuyu12138** [comment]
Well, I just want to know how to send the BackupDevice message to the hardware on the web side
