### ISSUE TITLE
Ethereum: small amounts might still be formatted incorrectly

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#210]
Ethereum app still formats some amounts incorrectly. I'm not really sure what we should do about this, because if someone sends `gas_price = 10003000000043` there's not much we can do about it. Maybe round up?

![photo5798628187075358153](https://user-images.githubusercontent.com/1835345/40723143-74b90132-641e-11e8-819f-ac269441f5c0.jpg)

Reported by @pankrats

Somewhat related to #154

**Comment by tsusanka** [comment]
Also, this happened on @szymonlesisz's new eth wallet, so maybe we should round up on that side?

**Comment by szymonlesisz** [comment]
I think this is just a temporary solution. No one can guarantee that other implementers will do the same (rounding up) on their wallets

**Comment by tsusanka** [comment]
Hm, good point. Well, leaving it overflow does not seem as a less scary/suspicious thing either but I guess it's better than what you're describing.

**Comment by tsusanka** [comment]
Similar thing on MEW. Also when you add another character (1 more) it gives an error `Invalid params: invalid hex value: Invalid character '.' at position 13.`.

![photo5801086437377028064](https://user-images.githubusercontent.com/1835345/40776030-e73d1ce2-64c9-11e8-876e-ba057d4d440a.jpg)

**Comment by Username123456765645** [comment]
I'm a noob but is it possible to make the text smaller I know it's a really crappy idea
