### ISSUE TITLE
Canceling from PC produces "unexpected message"

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-core#214]
When you send a `Cancel` message to a TT, you get back `FailureType.UnexpectedMessage`.
That should be `FailureType.ActionCancelled` instead.

see https://github.com/trezor/python-trezor/commit/ff5402842ca5650f70811f4dcb86ce1282fcea34#diff-680dbc8e79e141d1df4f7d7124c28446 for test case

**Comment by matejcik** [comment]
the test case is now failing `master`

**Comment by jpochyla** [comment]
Fixed by faccce5bd16197dff4cbbba1f67049c465dca766
