### ISSUE TITLE
Enforce BIP44 prefixes for new coins

### ISSUE THREAD

**Issue by jpochyla** [trezor/trezor-core#221]
In case of BIP44-like path, make sure it matches the coin. Do this also for non-Bitcoin-like altcoins.

**Comment by prusnak** [comment]
Also for BIP49 and BIP49 - the same logic.

**Comment by prusnak** [comment]
Also check in SignMessage and others, not just

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-core/commit/51df2499495cbf9337fcade365fc10c252dd1e79
