### ISSUE TITLE
text-splitting is broken for monospace font

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#224]
Unfortunately, I cannot send a picture from emulator since that freezes for some reason AND my phone camera is currently broken, so I cannot post screenshot

But when posting to cashaddr address, the address don't fit on display, probably because of `bitcoincash:` prefix.

That does not happen with Trezor One, since that does not show the `bitcoincash:` prefix.

**Comment by karel-3d** [comment]
Example:

This fits (despite showing the three dots for some reason), this is self-confirmation

![screenshot from 2018-06-11 12-44-40](https://user-images.githubusercontent.com/104945/41227513-5d7e8aae-6d75-11e8-937d-4b9059eff1d6.png)

This does not fit, same address, sending

![screenshot from 2018-06-11 12-45-10](https://user-images.githubusercontent.com/104945/41227576-9ff2d2e6-6d75-11e8-9265-1f4a585b9795.png)

**Comment by prusnak** [comment]
These are two issues actually. The first screenshot shows some bug in the line-splitting algorithm. This is for @jpochyla.

The length issue is fixed in 6c2c99688b5b0fb2a9f114b5e5b232b1c1a38e7c (we drop cashaddr prefix from the UI).

**Comment by jpochyla** [comment]
Fixed in 8e270fbabd694dd5f196774a4e63c755ecf5b456
