### ISSUE TITLE
zcash: transaction not valid

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#237]
Transaction from trezor is not a valid zcash transaction

Example

`030000807082c40301eeea5679f7962e61cc3b5887f091f583001035394331107a42f5bfa9091e3b82010000006a47304402200276266e3d2da96290eac33c2b265019b2085c7e931d93608014239acf907acb0220781ae8cd5b78ea604b93677c432f0663b0122b7b2730f1f66e9d4ed256b22a27012103a6109c45608b073dd3d1fee64d0a3a68664022c3b88741bcdb893bddc02d1e07ffffffff01629be111000000001976a914cc563dda440ed1e050818ce154111b13a66e7f4788ac000000000000000000`

=>

> 16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26

**Comment by prusnak** [comment]
Known issue, still trying to find the cause :-/

**Comment by karel-3d** [comment]
Hm. The scriptsig + scriptpubkey combined should evaluate correctly (when I parse the scripts semi-manually) - they are normal traditional scripts. Also not sure.

I will try to start zcash testnet server myself and just add "printfs" everywhere.

**Comment by karel-3d** [comment]
Maybe related to

https://github.com/zcash/zcash/issues/3327

**Comment by karel-3d** [comment]
It seems to be an actual zcash issue, not trezor issue.

**Comment by karel-3d** [comment]
The script is indeed not valid and the signature verification returns false on the stack . So I guess the signature is indeed not valid and the linked issue is unrelated.

I am comparing this code

https://github.com/zcash/zcash/blob/f0daf3915fd81fec7f0f79c4e109fdfaef44d162/src/script/interpreter.cpp#L1168

with this code

https://github.com/trezor/trezor-core/blob/master/src/apps/wallet/sign_tx/overwinter_zip143.py#L54

and it seems correct. I will try to do some step-by-step debugging I guess

**Comment by prusnak** [comment]
Another TX example: `030000807082c40301dc754d63eff4698ee321476872519c53f14cfe58c9425c7ee464c206461ef5aa010000006a473044022036556e76f99d0456eb893c5e8cbcae7fd615210c0b998c77de23e685c3064e8102201c90df2ecb753604e6ae805f225550bd48e730c9743ef05a5e29c945a5b2f9b60121030e669acac1f280d1ddf441cd2ba5e97417bf2689e4bbec86df4f831bf9f7ffd0ffffffff016c9be111000000001976a9145b157a678a10021243307e4bb58f36375aa80e1088ac000000000000000000`

**Comment by karel-3d** [comment]
I think I found it.

The problem is with blake2 hashing and the personal vs. key string.

In trezor-core, hashwriters are created like this

https://github.com/trezor/trezor-core/blob/3e2e5fa7b88d9b6f9b6a544aa3d092aec2751698/src/apps/wallet/sign_tx/overwinter_zip143.py#L26

Which creates the hash with the *key* 'ZcashPrevoutHash' (and others).

https://github.com/trezor/trezor-core/blob/3e2e5fa7b88d9b6f9b6a544aa3d092aec2751698/embed/extmod/modtrezorcrypto/modtrezorcrypto-blake2b.h#L52

However, zcash creates blake2 with *empty key*, but *personal* string (whatever it is).

https://github.com/zcash/zcash/blob/f0daf3915fd81fec7f0f79c4e109fdfaef44d162/src/hash.h#L177

The personal field is in trezor-crypto too.

https://github.com/trezor/trezor-crypto/blob/master/blake2b.c#L35

I could try to add that to the extmod, but it feels like totally dark and black magic to me.

**Comment by karel-3d** [comment]
Hm, it seems initialization with a different personal string needs to be also added to trezor-crypto.
