### ISSUE TITLE
Trezor Model T Upgrade: hold both buttons pressed.

### ISSUE THREAD

**Issue by rfjakob** [trezor/trezor-core#253]
I guess this is just a string that needs to be updated on beta-wallet.trezor.io , but the instruction to

> 2. When connecting, hold both buttons pressed.

is somewhat confusing on a Trezor Model T.

![screenshot from 2018-06-28 23-31-09](https://user-images.githubusercontent.com/286847/42061859-d76389aa-7b2b-11e8-87bf-36face07b3aa.png)

**Comment by prusnak** [comment]
Not a trezor-core issue and being fixed now, please close this
one. Thanks

**Comment by rfjakob** [comment]
Thanks!
