### ISSUE TITLE
Model T: v1 Protocol?

### ISSUE THREAD

**Issue by rfjakob** [trezor/trezor-core#254]
On https://github.com/trezor/trezor-core/issues/91#issuecomment-355759065 I read that

> T2 supports v1 protocol.

However, it seems to behave differently from a Model One. Testing with the tesoro Go library plus [this patch](https://github.com/rfjakob/tesoro/commit/0e43b88184b3f5648e4cb9d3d5a14e45ebe01926) I get:

Model One:
```
~/go/src/github.com/conejoninja/tesoro/example$ ./example 
Found 1 TREZOR devices connected
>init
{"vendor":"bitcointrezor.com"....}
```

Model T:
```
~/go/src/github.com/conejoninja/tesoro/example$ ./example 
Found 1 TREZOR devices connected
>init
(hangs)
```

The tesoro author seems to also have noticed this and says in https://github.com/conejoninja/tesoro/issues/7#issuecomment-401162052 :

> The new communication protocol is a *bit* different from model One

Now the question is: Is it different on purpose and should the library work around the difference, or maybe is v1 protocol support not yet complete? Thanks!

**Comment by matejcik** [comment]
I suspect this is because you're using HID interface. Trezor T talks only over WebUSB, and its HID interface is reserved for U2F.

Other than that, it speaks unmodified v1 protocol.

**Comment by rfjakob** [comment]
Ok I see, thanks for the clarification! The [API docs](https://wiki.trezor.io/Developers_guide:Low_level_API) left me confused.
