### ISSUE TITLE
makefile: flash_firmware needs to split writes across gap in sectors

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#265]
the firmware is large enough now that it fills up sectors across the split boundary outlined in memory.md. that is, there are two ranges of sectors, 6-11 and 17-23. the current make target writes everything linearly, bulldozing over sectors that it should not and that causes validation within the bootloader to fail. that's why `flash_firmware` fails to write a firmware successfully when `./trezorctl firmware_update` can write the same firmware.bin successfully. i'm not sure whether to do this all in the Makefile, or produce two chunks of the firmware.bin within SConscript.firmware and then use those within the Makefile target. probably doesn't matter and is just a style choice. any feedback welcome.

edit: note that this might also affect `flash_prodtest` at some time in the future (it depends on the FIRMWARE_START variable in the Makefile).

**Comment by prusnak** [comment]
Sconscript.firmware already creates two chunks called
`firmware.bin.p{1,2}`, so let's use those two.

**Comment by prusnak** [comment]
I fixed that in c4918cea9746184c0616eede15da3c9b55d24149, but I still get the error when starting firmware flashed via openocd (bootloader shows initial state as if there were no firmware present).

**Comment by mcudev** [comment]
got it https://github.com/trezor/trezor-core/pull/266

**Comment by mcudev** [comment]
closing, fixed by https://github.com/trezor/trezor-core/commit/c4918cea9746184c0616eede15da3c9b55d24149 and https://github.com/trezor/trezor-core/pull/266
thanks!
