### ISSUE TITLE
Fixing of incorrect signing of Zencash transactions 

### ISSUE THREAD

**Issue by idimon4uk** [trezor/trezor-core#277]
https://github.com/trezor/trezor-core/blob/9541662902337c94f0a6282654c8a0ffb1e49821/src/apps/common/coininfo.py#L460
Hello Pavol , Here should be "None" instead of '0'. We get incorrect signed transactions as the result if here is '0'. I would be grateful for your fix and feedback.

**Comment by idimon4uk** [comment]
@prusnak

**Comment by prusnak** [comment]
Fixed in ca7a9110339a38f36eeef67314c3d66e96cf3376

**Comment by idimon4uk** [comment]
Thank you very much
