### ISSUE TITLE
Interuption of Seed Backup leads to Inconsistant State 

### ISSUE THREAD

**Issue by da2ce7** [trezor/trezor-core#283]
When Writing Down a New Seed for Trezor Original, I was disconnected from the internet.

The surprising result upon reloading the page was that the Trezor behaved if I had successfully verified my code and completed the seed backup process:

- It didn't allow me to complete the backup process.

I find this result as dangerous and unexpected.

**Comment by prusnak** [comment]
If you use the latest firmware (1.6.2), the failed backup will show a "BACKUP FAILED" message on the device display.

**Comment by prusnak** [comment]
This is planned to be shown in the web-ui.
