### ISSUE TITLE
Chromeos

### ISSUE THREAD

**Issue by rodasmith** [trezor/trezor-core#284]
When the Chrome extension is disabled, there does not appear to be any option to access funds through ChromeOS. Will the Bridge or any other technology let ChromeOS users access funds?

**Comment by rodasmith** [comment]
Maybe this issue should be closed here and moved to https://github.com/trezor/trezor-chrome-extension/issues

**Comment by prusnak** [comment]
You can use Chrom Extension or WebUSB (for Model T and eventually Trezor
One). Please close the issue.
