### ISSUE TITLE
Add support for Ontology

### ISSUE THREAD

**Issue by backslash47** [trezor/trezor-core#294]
Hello,
I am an independent contributor to Ontology blockchain codebase. I implemented the first version of necessary methods (getAddress, getPublicKey and signTx) which is correctly working with the Ontology blockchain. 
I know about few shortcomings in my code, which I will be working on. What will be the correct way to submit the ready code for review and including the code into codebase?

The codes can be found at:
https://github.com/backslash47/trezor-core
https://github.com/backslash47/trezor-common
https://github.com/backslash47/python-trezor

**Comment by prusnak** [comment]
The correct process is to send a pull request to the `trezor-common` repository. Once this has been merged in, you can send pull requests to the `trezor-core` and `python-trezor` repos for review. I am going to close this issue and I'm looking forward for the PRs.

**Comment by backslash47** [comment]
Thanks, I will work on it a little more and when I am satisfied the PR will be there.
