### ISSUE TITLE
Cardano: signTransaction

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#305]
CardanoSignTransaction message shows on device display:

First screen: negative fee value
Second screen: confirm output address (ok)
Third screen: confirm output amount (ok)
Fourth screen: confirm change (derivation path instead of address)
Fifth screen: confirm change amount

Is there any reason why we are showing/confirming change address? we don't do this in other coins
I think this message should have the same flow as other coins, so:

1. confirm outputs and amounts
2. confirm fee
3. done
![negative-fee](https://user-images.githubusercontent.com/3435913/44027951-9f19b100-9ef8-11e8-84ef-950a35ca4399.png)
![confirm-change](https://user-images.githubusercontent.com/3435913/44027955-a2ecf0e4-9ef8-11e8-8e36-c386431df5a2.png)

**Comment by prusnak** [comment]
@jmuravsky any comments on this?

If there is no special reason for this, I'd remove the screens 4 and 5 (confirmation of change address and change amount) and move the fee screen after the ouputs/amounts screens. Also we'll show the fee as positive value.

**Comment by jmuravsky** [comment]
the change address/value are there because thats something we wanted to use on cardanolite (we only use a range of 10 addresses, so change going to address outside of that range would be invisible to our wallet) but its not inherently neccessary, just something that kind of improves the secure "feel". 

as for the negative fee, that seems like a genuine bug, ill look into the code but i remember showing a positive fee usually.

**Comment by jmuravsky** [comment]
so checked the code, and the fee should indeed be a positive number. Its however implicit (we expect caller to calculate the fee and subtract it from the change amount) as can be seen here: 
https://github.com/trezor/trezor-core/blob/master/src/apps/cardano/sign_transaction.py#L222
so it is entirely possible that the input/output amounts for the above mentioned transaction just didnt add up properly?

**Comment by szymonlesisz** [comment]
sorry, looks like my fault. I've accidentally send inputs: undefined into device.
Hovever shouldn't this field be obligatory? Is it possible to sign cardano tx without inputs?

**Comment by ddeath** [comment]
If no inputs will be send, then the signed transaction will be rejected when submitting to the blockchain so yes it would make sense to add the check for the inputs

**Comment by tsusanka** [comment]
@szymonlesisz will try this and let us know

**Comment by szymonlesisz** [comment]
confirmed, now i see valid absolute numbers

**Comment by ddeath** [comment]
@szymonlesisz just out of curiosity, I was always curios what should I do when I wanted to cancel that operation? just unplug the trezor from computer? That was probably the reason why I did not use it, I felt like I was lost because that one thing was not clear to me as the user

**Comment by tsusanka** [comment]
@ddeath we are aware of it and it is something we are discussing continuously. We want to revisit all Trezor T UI and this is something we'll tackle as well - #380

**Comment by tsusanka** [comment]
We have agreed we'll modify this later (adding the hold button) as part of #380.
