### ISSUE TITLE
Cardano: getAddres + getPublicKey

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#306]
CardanoGetAddress shows:

1. export address confirmation
2. derivation path confirmation

![getaddress](https://user-images.githubusercontent.com/3435913/44028193-644f4a48-9ef9-11e8-8f1b-10f36a2238e5.png)

CardanoGetPubliKey shows:
 - derivation path confirmation 

![getpublickey](https://user-images.githubusercontent.com/3435913/44028206-6c925470-9ef9-11e8-833b-b9b97bd9db8b.png)

I think in both cases there shouldn't be derivation path confirmation, it's not intuitive for the user

**Comment by tsusanka** [comment]
I've removed the bip-32 display. The getPublicKey and GetAddress messages will be probably merged later but that's part of #308

**Comment by refi93** [comment]
@tsusanka we decided to display the derivation path to the user so they can be sure that the returned address does indeed belong to some "normal" derivation path.

Our line of thinking was that a man in the middle may somehow tamper with the derivation path sent by the wallet client to Trezor (for example setting 0' to 84927383'). A wallet usually works over a small range of addresses (e.g. 0' to 10') and may cause loss of funds in the sense that the client may then receive to this "spoiled" address the funds which will be subsequently unaccessible by the wallet client he is using. Did you consider this scenario? Is it actually a concern? If not, why?

**Comment by prusnak** [comment]
@refi93 This is in process of unification and refactoring, where we would like to unify dialogs across various coins to look similar. See https://github.com/trezor/trezor-core/issues/320 - where we address this.

**Comment by refi93** [comment]
@prusnak I see, so can we expect in the foreseeable future that the derivation path will be displayed in this case?

**Comment by tsusanka** [comment]
Yes, exactly. Sorry about that, I should have pointed it out here as well
