### ISSUE TITLE
boardloader: sdcard flash timed warning or user confirm

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#31]
Right now if you have a properly configured microSD card in the the slot at reset, then the boardloader nearly instantly starts erasing flash memory.

Perhaps it would be safer to get a user confirmation, or show a N-second timed count down warning until re-flashing starts?

I do want to keep the boardloader simple though. Maybe it's OK as-is since a user would have to go out of their way to have such a microSD card inserted? Feel free to close if that's how you feel, or leave open as a todo.

**Comment by prusnak** [comment]
Delay seems fine, will implement it.

**Comment by prusnak** [comment]
Implemented in 9c3631f470fced01d78cc5ea8d59e6d215a5e208

**Comment by mcudev** [comment]
Thanks!
Reminds me of Inspector Gadget, "this message will self-destruct..." :)
My only feedback is that maybe a longer time could be used, 10 - 15 seconds etc... but that's more of a usability question.
