### ISSUE TITLE
Remove Stellar(Get)PublicKey

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#325]
Remove StellarGetPublicKey and StellarPublicKey messages? The sign/verify functions were removed so I'm not sure we want to keep this

**Comment by tsusanka** [comment]
@zulucrypto is that okay for you? The pubkey is not used anywhere now, so I think it's better when we remove it. In case the sign/verify functions return, we'll restore this as well

**Comment by zulucrypto** [comment]
I was planning on using this method when I implemented support for the [account viewer](https://www.stellar.org/account-viewer/) so I think it's still necessary.

Usually people only have one Stellar address that they use multiple times, so this method is important to allow people to get their public address that they can share with others.

**Comment by tsusanka** [comment]
I'm confused. Isn't that what's GetAddress for?

**Comment by tsusanka** [comment]
Removed in 4305c1da1bd89582ce4d05def815e6c5a182e35f
