### ISSUE TITLE
Chrome does not display Trezor T webusb popup on normal FW, only on bootloader

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#335]
For some reason, on macOS (and probably on Windows too), firmware doesn't trigger the Chrome popup when plugged in in FW mode.

It *does* display the pop-up in bootloader mode.

That leads me to think the webusb descriptor is somehow wrong in the firmware. (The webusb transport on beta-wallet works normally in both, because the webusb descriptor is optional.)

It's not such a big issue since user first gets the device in bootloader mode and sees the pop-up.

**Comment by prusnak** [comment]
It's a feature not a bug.

**Comment by prusnak** [comment]
See https://github.com/trezor/trezor-core/issues/170
