### ISSUE TITLE
Should we allow empty path?

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#343]
Currently, when an empty path is provided trezor still returns a public key / address. Is that desired or should it return an error?

**Comment by prusnak** [comment]
let's return an error

**Comment by tsusanka** [comment]
This is a straightforward issue, but unfortunetely many tests use empty path. I guess I remove those or regenerate

**Comment by prusnak** [comment]
Please regenerate such tests.

**Comment by tsusanka** [comment]
Unfortunetly there is a small catch with Bitcoin signing, which does this: https://github.com/trezor/trezor-core/blob/master/src/apps/wallet/sign_tx/__init__.py#L22

We can either:
- derive the path later during singing, but this needs another helper class to fit the workflow
- have a dummy flag `derive_node(allow_root=False)` in seed.py

**Comment by jpochyla** [comment]
I suggest we go with 1)

**Comment by tsusanka** [comment]
Let's do it as part of https://github.com/trezor/trezor-core/pull/411 . @jpochyla 	can I assign this to you so you can do it as part of the PR?
