### ISSUE TITLE
Return correct xpub based on script_type

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#344]
Xpubs [differ](https://github.com/satoshilabs/slips/blob/master/slip-0132.md#registered-hd-version-bytes) based on script_type. GetPublicKey now has the field, but trezor does not support it yet.

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-core/commit/ebdd8c9b07537351c7dedec4db6e1fcbeb0426ef
