### ISSUE TITLE
Validate GetPublicKey path against a script_type

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#345]
Check that GetPublicKey's path's purpose matches against the script_type.

Connected to #344

**Comment by tsusanka** [comment]
We've implemented this as part of #341, is that it?
```python
    """
    Validates purpose against provided input's script type:
    - 44 for spending address (script_type == SPENDADDRESS)
    - 48 for multisig (script_type == SPENDMULTISIG)
    - 49 for p2sh-segwit spend (script_type == SPENDP2SHWITNESS)
    - 84 for native segwit spend (script_type == SPENDWITNESS)
    """
    if purpose == 44 | HARDENED and script_type != InputScriptType.SPENDADDRESS:
        return False
    if purpose == 48 | HARDENED and script_type != InputScriptType.SPENDMULTISIG:
        return False
    if (  # p2wsh-nested-in-p2sh
        purpose == 49 | HARDENED and script_type != InputScriptType.SPENDP2SHWITNESS
    ):
        return False
    if (  # p2wsh
        purpose == 84 | HARDENED and script_type != InputScriptType.SPENDWITNESS
    ):
        return False
    return True
```

**Comment by tsusanka** [comment]
> Yes, the conditions seem right, but I don't see it being used here: /src/apps/wallet/get_public_key.py@master

Yeah, it's not there at the moment due to #406. So, I'll add it as you suggest. Should it produce ProcessError or just a UI warning (as for unknown paths)?

**Comment by prusnak** [comment]
Let's make this consistent with the other (sign) behaviour.

**Comment by tsusanka** [comment]
Can we assume all other Bitcoin-like coins will use 44' with SPEND_ADDRESS? Becuase I've just realised I do not know what coin is present (due to https://github.com/trezor/trezor.js/issues/73) so I'm doing this check for all bitcoin-like coins. So in case there is some mismatch with Bitcoin we're screwed.

**Comment by tsusanka** [comment]
Hm, I'm afraid I've found another incosistency with trezor wallet. It sends GetPublicKet with 49' but doesn't set the script_type (leaves it empty). I'll confirm with szymon

**Comment by szymonlesisz** [comment]
confirmed.

Old wallet (trezor.js)

https://github.com/trezor/trezor.js/blob/master/src/session.js#L169-L174

New wallet (connect.js)

https://github.com/trezor/connect/blob/develop/src/js/device/DeviceCommands.js#L94-L140

**Comment by tsusanka** [comment]
I guess wallet can add this, but does it have any advantages? There are checks if the purpose is in {44', 48', 49', 84'} and if the coin has segwit then that it is in {44', 48'}. Isn't that enough?

**Comment by prusnak** [comment]
Correct script_type handling in get_public_key (xpub/ypub) is implemented since 1.7.1 and 2.0.8

**Comment by tsusanka** [comment]
This is basicaly implemented, but I will wait for https://github.com/trezor/trezor-core/pull/341 to be merged, because I need to build on top of it and at the same time I do not want to mix those two together (because this issue requires the aforementioned frontend fixes, so will be merged later).

**Comment by tsusanka** [comment]
This is implemented in `tsusanka/eth-get-public-key` (along with Ethereum GetPublicKey) and will be merged when frontend is completely ready. I'm closing here, and we'll track in https://github.com/trezor/trezor-core/issues/406
