### ISSUE TITLE
ethereumSignTransaction: chain_id out of bounds (using ganache)

### ISSUE THREAD

**Issue by brunobar79** [trezor/trezor-core#346]
I'm trying to sign a transaction via metamask connected to a local instance of ganache-cli.
Ganache is using a chain_id = 1536078068339

While trying to sign the transaction I'm getting an error: chain_id out of bounds

I think this issue was reported before at https://github.com/trezor/connect/issues/137 and fixed on  trezor-mcu via https://github.com/trezor/trezor-mcu/pull/381

**Comment by prusnak** [comment]
We only support chains with chain_id < 2^32. Sorry
