### ISSUE TITLE
Cardano shouldn't be allowed to sign an arbitrary message

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#347]
It seems to me that Cardano signs an arbitrary message with no prefix. This is dangerous because when a malicious party provides some data with a special meaning (let's say a bitcoin transaction) it gets signed using this method. #341 also tries to address this but there should be some prefix for every message Trezor signs (see [Ethereum](https://github.com/trezor/trezor-core/blob/master/src/apps/ethereum/sign_message.py#L14) or [Lisk](https://github.com/trezor/trezor-core/blob/master/src/apps/lisk/sign_message.py)).

Also another good idea is to allow ASCII only messages.

@ddeath could you look into this?

**Comment by tsusanka** [comment]
Also, @ddeath do you use those sign/verify functions in your wallet in particular or did you implement them just for some future use?

**Comment by tsusanka** [comment]
Also another good idea is to allow ASCII only messages.

**Comment by ddeath** [comment]
@tsusanka we do not plan to use them for now so it could be removed.

**Comment by tsusanka** [comment]
Ok, let's remove it. I'll do it

**Comment by tsusanka** [comment]
Removed in https://github.com/trezor/trezor-core/commit/c0770ad13151a97235c9395775b8ddbabd16252a, https://github.com/trezor/trezor-common/commit/843facd2c18b22cefea2ba6e14cbad509d91988f and https://github.com/trezor/python-trezor/commit/4f572f9e158dc8a286f37c3f2a03ca6fdae6f415. Let me know, if I've missed something

**Comment by tsusanka** [comment]
And https://github.com/trezor/trezor-core/commit/7128337031fd6dd6347db5fa32c6f1d983f2a3a4 ..

**Comment by ddeath** [comment]
it should probably be removed also from `connect`

**Comment by ddeath** [comment]
@tsusanka also python-trezor does not have updated trezor-common reference
