### ISSUE TITLE
Stellar: Returned signature is too long

### ISSUE THREAD

**Issue by zulucrypto** [trezor/trezor-core#349]
Hi @tsusanka ,
I noticed while testing in the emulator that the signature that comes back from "stellar sign tx" is base64-decoding to 96 bytes when it should be 64.

To reproduce:

1. https://trezor.github.io/connect-explorer/#/stellar-signtx
2. Sign the default transaction with the Model T emulator
3. Signature is `c8459966df9a97ece185928fe5a30bf35e67faa4d2cc0976ad5840f139b3d5e7b93b1ded223463aac8423595a5b356a8c62be123207828afcf23e7c1fdb26700`

If you could add a quick example test for `sign_tx` to get me started I can fill it in with some more operations or a failing test for this issue.

**Comment by prusnak** [comment]
The signature is hex-encoded (128 hexdigits = 64 bytes), not Base64 encoded.

**Comment by tsusanka** [comment]
Hi,
I sure can help, but I'm not sure I understand the issue. It seems `sign_tx` returns 64 bytes, is that incorrect?

StellarSignedTx returns the signature as bytes in hex (no base64 encoding), is that maybe the misunderstanding?

**Comment by zulucrypto** [comment]
Thank you both, I wasn't decoding it correctly
