### ISSUE TITLE
Show confirmation when creating new seed

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-core#362]
Since we split device initialization and backup into two separate workflows, there's no on-device confirmation when device is creating new seed. Therefore incautious user, may easily generate new seed without noticing that.

reset_device workflow should implement confirmation screen telling user new seed is going to be created (eg "Create new wallet?" (or seed?)).

**Comment by prusnak** [comment]
Implemented in a0a195fdd39be13fc268a778ed869f95a24d81e3
