### ISSUE TITLE
Monero: protobuf changes

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#368]
- [x] merge step 8 into step 7 or find a better name for step 8 (I think the first one is a better choice)
- [x] remove MoneroTransactionInitAck.in_memory, many_inputs, many_outputs?
- [x] rename MoneroTransactionSignInputRequest.alpha_enc to MoneroTransactionSignInputRequest.alpha ? Or maybe better MoneroTransactionSignInputRequest.pseudo_out_alpha?

----

- [x] please verify this, but `MoneroRctKey` message contains two fields `dest` and `mask`. `dest` is used for the one-time address' public key, which is fine, but `mask` is used for the full `commitment`, also when the mask is completely unknown.  That's confusing, I suggest to rename it to `commitment`

**Comment by ph4r05** [comment]
`MoneroRctKey` is equivalent for Monero `rct::ctkey`:

```
    //containers For CT operations
    //if it's  representing a private ctkey then "dest" contains the secret key of the address
    // while "mask" contains a where C = aG + bH is CT pedersen commitment and b is the amount
    // (store b, the amount, separately
    //if it's representing a public ctkey, then "dest" = P the address, mask = C the commitment
```

https://github.com/monero-project/monero/blob/5c85da5a73424017ea9c340a0412f90356d77358/src/ringct/rctTypes.h#L91

We may add a comment to the fields.

**Comment by tsusanka** [comment]
Ugh, that's just dull. We use it for both "private" and "public" I guess, right?

I still suggest to rename it if possible (we can do MoneroRctKey{Private,Public}), or is it too much of a hassle?

**Comment by ph4r05** [comment]
I've made it MoneroRctKeyPublic as in the protocol we use only commitment variant. 

Once the https://github.com/trezor/trezor-common/pull/216 gets merged I would need version bump in python-trezor also. 

I have already finished modifications to both trezor-core PR and monero-agent so after trezor-common is ready I can apply those changes. Then I will also update monero-doc and monero/readme.md

**Comment by tsusanka** [comment]
I can close this, right?

**Comment by ph4r05** [comment]
ok for me
