### ISSUE TITLE
Show number of keys required for multisig address in Confirm address screen

### ISSUE THREAD

**Issue by stepansnigirev** [trezor/trezor-core#376]
When setting up a new m-of-n multisig address I can't be sure that m and n are not changed by the software. I can't say if the address shown on the screen is 2-of-3 or 1-of-4 multisig.

Say, I use 3 hardware wallets and try to setup 2-of-3 multisig wallet.
Attacker can replace my 2-of-3 address by 1-of-4 address (adding one extra key that he owns). Then I can use the wallet as usual for some time but when I have enough money attacker can steal all that money with just his key.

To prevent this it is crucial to display both m and n on the device.

**Comment by prusnak** [comment]
Right, we do that on Trezor One and this will be addressed for Trezor Core.

**Comment by prusnak** [comment]
Fixed via 939a93221941df8d454569a674f6fb082bf1d423
