### ISSUE TITLE
T1: EthereumGetAddress misleading account description

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#378]
T1, FW 1.6.3.
params
- address_n: [2147483692, 2147483708, 2147483648, 0, 2] (m/44'/60'/0'/0/2)
- show_display: true

result
address on display is valid but account description always says "ETH account 1". Which is fine according to BIP44 but since we agreed on that ethereum address == ethereum account it's confusing to user.
Maybe there should be "address [N]" instead?

**Comment by prusnak** [comment]
Fixed in 8e6369e1ba8e7c59a061f804b392893961d6f77b

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/8e6369e1ba8e7c59a061f804b392893961d6f77b

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/e1700c2ce12dd652784dd995ee4b0ff43a096f7a
