### ISSUE TITLE
DEBUG_BUILD=1 make build_unix build failed with [ /usr/bin/ld: cannot find -lgcc_s ]

### ISSUE THREAD

**Issue by sarveshwar-singh** [trezor/trezor-core#379]
++++++++++++++++++++++++++
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

arch: x86_64
++++++++++++++++++++++++++

DEBUG_BUILD=1 make build_unix 
failed with below error:
---------------------------------------------
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
scons: *** [build/unix/micropython] Error 1
Makefile:119: recipe for target 'build_unix' failed
make: *** [build_unix] Error 2
---------------------------------------------

**Comment by prusnak** [comment]
Not related to trezor-core, but rather an issue with Ubuntu installation.

Try installing the package `build-essential`or try Googling for "cannot find lgcc_s ubuntu. If you find the solution, please post it here.
