### ISSUE TITLE
Cardano signing tx is not working

### ISSUE THREAD

**Issue by ddeath** [trezor/trezor-core#382]
In the commit https://github.com/trezor/trezor-core/commit/addbdd89371efdf10b5e5b13f558060557e50489#diff-5126cfe948ea95d282c8225618fedf9bR57 was introduced change which breaks the signing of transactions on trezor UI.

The old code returned `list` the new code return `generator` and then it fails when it tries to `chunks` that output because generator does not support `len()`

**Comment by ddeath** [comment]
Hi just added test coverage for this in https://github.com/trezor/python-trezor/pull/329

This case was not covered because it failed on showing change address. But if the change address was not provided (like in the old test) then ui screen was not invoked.

I added change address to the test

**Comment by prusnak** [comment]
Great!
