### ISSUE TITLE
Build error on RaspberryPi @ 4.14.71-v7+: undefined reference to `nlr_jump' / 'nlr_push'

### ISSUE THREAD

**Issue by okipol88** [trezor/trezor-core#384]
Hello,

I get a build error when compiling make `build_unix` (or rather it seems a linker error when linking *.o files).
The micropython itself is compilable when first compilig the `axtls` library.

`gcc -o build/unix/micropython build/unix/embed/extmod/modtrezorconfig/modtrezorconfig.o build/unix/embed/extmod/modtrezorconfig/norcow.o build/unix/embed/extmod/modtrezorconfig/storage.o build/unix/embed/extmod/modtrezorcrypto/modtrezorcrypto.o build/unix/embed/extmod/modtrezorcrypto/crc.o build/unix/vendor/trezor-crypto/address.o build/unix/vendor/trezor-crypto/aes/aescrypt.o build/unix/vendor/trezor-crypto/aes/aeskey.o build/unix/vendor/trezor-crypto/aes/aes_modes.o build/unix/vendor/trezor-crypto/aes/aestab.o build/unix/vendor/trezor-crypto/base58.o build/unix/vendor/trezor-crypto/base32.o build/unix/vendor/trezor-crypto/bignum.o build/unix/vendor/trezor-crypto/bip32.o build/unix/vendor/trezor-crypto/bip39.o build/unix/vendor/trezor-crypto/blake256.o build/unix/vendor/trezor-crypto/blake2b.o build/unix/vendor/trezor-crypto/blake2s.o build/unix/vendor/trezor-crypto/curves.o build/unix/vendor/trezor-crypto/ecdsa.o build/unix/vendor/trezor-crypto/chacha20poly1305/chacha20poly1305.o build/unix/vendor/trezor-crypto/chacha20poly1305/chacha_merged.o build/unix/vendor/trezor-crypto/chacha20poly1305/poly1305-donna.o build/unix/vendor/trezor-crypto/chacha20poly1305/rfc7539.o build/unix/vendor/trezor-crypto/ed25519-donna/curve25519-donna-32bit.o build/unix/vendor/trezor-crypto/ed25519-donna/curve25519-donna-helpers.o build/unix/vendor/trezor-crypto/ed25519-donna/curve25519-donna-scalarmult-base.o build/unix/vendor/trezor-crypto/ed25519-donna/ed25519.o build/unix/vendor/trezor-crypto/ed25519-donna/ed25519-donna-32bit-tables.o build/unix/vendor/trezor-crypto/ed25519-donna/ed25519-donna-basepoint-table.o build/unix/vendor/trezor-crypto/ed25519-donna/ed25519-donna-impl-base.o build/unix/vendor/trezor-crypto/ed25519-donna/ed25519-keccak.o build/unix/vendor/trezor-crypto/ed25519-donna/ed25519-sha3.o build/unix/vendor/trezor-crypto/ed25519-donna/modm-donna-32bit.o build/unix/vendor/trezor-crypto/groestl.o build/unix/vendor/trezor-crypto/hasher.o build/unix/vendor/trezor-crypto/hmac.o build/unix/vendor/trezor-crypto/memzero.o build/unix/vendor/trezor-crypto/nist256p1.o build/unix/vendor/trezor-crypto/pbkdf2.o build/unix/vendor/trezor-crypto/rand.o build/unix/vendor/trezor-crypto/ripemd160.o build/unix/vendor/trezor-crypto/secp256k1.o build/unix/vendor/trezor-crypto/sha2.o build/unix/vendor/trezor-crypto/sha3.o build/unix/vendor/trezor-crypto/nem.o build/unix/embed/extmod/modtrezorio/modtrezorio.o build/unix/embed/extmod/modtrezorui/display.o build/unix/embed/extmod/modtrezorui/inflate.o build/unix/embed/extmod/modtrezorui/font_bitmap.o build/unix/embed/extmod/modtrezorui/font_roboto_bold_20.o build/unix/embed/extmod/modtrezorui/font_roboto_regular_20.o build/unix/embed/extmod/modtrezorui/font_robotomono_bold_20.o build/unix/embed/extmod/modtrezorui/font_robotomono_regular_20.o build/unix/embed/extmod/modtrezorui/modtrezorui.o build/unix/embed/extmod/modtrezorui/trezor-qrenc/qr_encode.o build/unix/embed/extmod/modtrezorutils/modtrezorutils.o build/unix/vendor/micropython/ports/unix/modtime.o build/unix/vendor/micropython/extmod/modubinascii.o build/unix/vendor/micropython/extmod/moductypes.o build/unix/vendor/micropython/extmod/moduheapq.o build/unix/vendor/micropython/extmod/modutimeq.o build/unix/vendor/micropython/extmod/utime_mphal.o build/unix/vendor/micropython/lib/mp-readline/readline.o build/unix/vendor/micropython/py/argcheck.o build/unix/vendor/micropython/py/asmarm.o build/unix/vendor/micropython/py/asmbase.o build/unix/vendor/micropython/py/asmthumb.o build/unix/vendor/micropython/py/asmx64.o build/unix/vendor/micropython/py/asmx86.o build/unix/vendor/micropython/py/asmxtensa.o build/unix/vendor/micropython/py/bc.o build/unix/vendor/micropython/py/binary.o build/unix/vendor/micropython/py/builtinevex.o build/unix/vendor/micropython/py/builtinhelp.o build/unix/vendor/micropython/py/builtinimport.o build/unix/vendor/micropython/py/compile.o build/unix/vendor/micropython/py/emitbc.o build/unix/vendor/micropython/py/emitcommon.o build/unix/vendor/micropython/py/emitglue.o build/unix/vendor/micropython/py/formatfloat.o build/unix/vendor/micropython/py/frozenmod.o build/unix/vendor/micropython/py/gc.o build/unix/vendor/micropython/py/lexer.o build/unix/vendor/micropython/py/malloc.o build/unix/vendor/micropython/py/map.o build/unix/vendor/micropython/py/modarray.o build/unix/vendor/micropython/py/modbuiltins.o build/unix/vendor/micropython/py/modgc.o build/unix/vendor/micropython/py/modmath.o build/unix/vendor/micropython/py/modmicropython.o build/unix/vendor/micropython/py/modstruct.o build/unix/vendor/micropython/py/modsys.o build/unix/vendor/micropython/py/mpprint.o build/unix/vendor/micropython/py/mpstate.o build/unix/vendor/micropython/py/mpz.o build/unix/vendor/micropython/py/nativeglue.o build/unix/vendor/micropython/py/nlr.o build/unix/vendor/micropython/py/nlrx86.o build/unix/vendor/micropython/py/nlrx64.o build/unix/vendor/micropython/py/obj.o build/unix/vendor/micropython/py/objarray.o build/unix/vendor/micropython/py/objattrtuple.o build/unix/vendor/micropython/py/objbool.o build/unix/vendor/micropython/py/objboundmeth.o build/unix/vendor/micropython/py/objcell.o build/unix/vendor/micropython/py/objclosure.o build/unix/vendor/micropython/py/objcomplex.o build/unix/vendor/micropython/py/objdict.o build/unix/vendor/micropython/py/objenumerate.o build/unix/vendor/micropython/py/objexcept.o build/unix/vendor/micropython/py/objfilter.o build/unix/vendor/micropython/py/objfloat.o build/unix/vendor/micropython/py/objfun.o build/unix/vendor/micropython/py/objgenerator.o build/unix/vendor/micropython/py/objgetitemiter.o build/unix/vendor/micropython/py/objint_longlong.o build/unix/vendor/micropython/py/objint_mpz.o build/unix/vendor/micropython/py/objint.o build/unix/vendor/micropython/py/objlist.o build/unix/vendor/micropython/py/objmap.o build/unix/vendor/micropython/py/objmodule.o build/unix/vendor/micropython/py/objnamedtuple.o build/unix/vendor/micropython/py/objnone.o build/unix/vendor/micropython/py/objobject.o build/unix/vendor/micropython/py/objpolyiter.o build/unix/vendor/micropython/py/objproperty.o build/unix/vendor/micropython/py/objrange.o build/unix/vendor/micropython/py/objreversed.o build/unix/vendor/micropython/py/objset.o build/unix/vendor/micropython/py/objsingleton.o build/unix/vendor/micropython/py/objslice.o build/unix/vendor/micropython/py/objstr.o build/unix/vendor/micropython/py/objstringio.o build/unix/vendor/micropython/py/objstrunicode.o build/unix/vendor/micropython/py/objtuple.o build/unix/vendor/micropython/py/objtype.o build/unix/vendor/micropython/py/objzip.o build/unix/vendor/micropython/py/opmethods.o build/unix/vendor/micropython/py/parse.o build/unix/vendor/micropython/py/parsenum.o build/unix/vendor/micropython/py/parsenumbase.o build/unix/vendor/micropython/py/persistentcode.o build/unix/vendor/micropython/py/qstr.o build/unix/vendor/micropython/py/reader.o build/unix/vendor/micropython/py/repl.o build/unix/vendor/micropython/py/runtime_utils.o build/unix/vendor/micropython/py/runtime.o build/unix/vendor/micropython/py/scope.o build/unix/vendor/micropython/py/scheduler.o build/unix/vendor/micropython/py/sequence.o build/unix/vendor/micropython/py/showbc.o build/unix/vendor/micropython/py/smallint.o build/unix/vendor/micropython/py/stackctrl.o build/unix/vendor/micropython/py/stream.o build/unix/vendor/micropython/py/unicode.o build/unix/vendor/micropython/py/vm.o build/unix/vendor/micropython/py/vstr.o build/unix/vendor/micropython/py/warning.o build/unix/vendor/micropython/ports/unix/gccollect.o build/unix/vendor/micropython/ports/unix/unix_mphal.o build/unix/vendor/micropython/ports/unix/input.o build/unix/vendor/micropython/ports/unix/alloc.o build/unix/embed/unix/common.o build/unix/embed/unix/profile.o build/unix/embed/unix/flash.o build/unix/embed/unix/main.o build/unix/embed/unix/rng.o build/unix/embed/unix/sdcard.o build/unix/embed/unix/sbu.o build/unix/embed/unix/touch.o build/unix/embed/unix/usb.o -lm -lSDL2_image -lSDL2 
build/unix/vendor/micropython/py/bc.o: In function `fun_pos_args_mismatch':
/home/pi/projects/git/trezor-core/vendor/micropython/py/bc.c:85: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/bc.o: In function `mp_setup_code_state':
/home/pi/projects/git/trezor-core/vendor/micropython/py/bc.c:208: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objgenerator.o: In function `gen_instance_send':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objgenerator.c:191: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objgenerator.o: In function `gen_resume_and_raise':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objgenerator.c:180: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objgenerator.o: In function `gen_instance_close':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objgenerator.c:226: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objstr.o:/home/pi/projects/git/trezor-core/vendor/micropython/py/objstr.c:2104: more undefined references to `nlr_jump' follow
build/unix/embed/unix/main.o: In function `execute_from_lexer':
/home/pi/projects/git/trezor-core/embed/unix/main.c:105: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/embed/unix/main.c:148: undefined reference to `nlr_jump'
build/unix/embed/unix/main.o: In function `main_':
/home/pi/projects/git/trezor-core/embed/unix/main.c:562: undefined reference to `nlr_push'
build/unix/vendor/micropython/extmod/moductypes.o: In function `uctypes_struct_subscr':
/home/pi/projects/git/trezor-core/vendor/micropython/extmod/moductypes.c:544: undefined reference to `nlr_jump'
build/unix/vendor/micropython/extmod/modutimeq.o: In function `mod_utimeq_peektime':
/home/pi/projects/git/trezor-core/vendor/micropython/extmod/modutimeq.c:170: undefined reference to `nlr_jump'
build/unix/vendor/micropython/extmod/modutimeq.o: In function `mod_utimeq_heappop':
/home/pi/projects/git/trezor-core/vendor/micropython/extmod/modutimeq.c:145: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/argcheck.o: In function `mp_arg_check_num':
/home/pi/projects/git/trezor-core/vendor/micropython/py/argcheck.c:58: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/argcheck.o: In function `mp_arg_parse_all':
/home/pi/projects/git/trezor-core/vendor/micropython/py/argcheck.c:91: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/builtinevex.o: In function `code_execute':
/home/pi/projects/git/trezor-core/vendor/micropython/py/builtinevex.c:62: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/vendor/micropython/py/builtinevex.c:72: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/builtinimport.o: In function `do_execute_raw_code':
/home/pi/projects/git/trezor-core/vendor/micropython/py/builtinimport.c:167: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/vendor/micropython/py/builtinimport.c:179: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/builtinimport.o: In function `mp_builtin___import__':
/home/pi/projects/git/trezor-core/vendor/micropython/py/builtinimport.c:404: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/compile.o: In function `mp_compile_to_raw_code':
/home/pi/projects/git/trezor-core/vendor/micropython/py/compile.c:3502: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/modbuiltins.o: In function `mp_builtin_ord':
/home/pi/projects/git/trezor-core/vendor/micropython/py/modbuiltins.c:350: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/modbuiltins.o: In function `mp_builtin_next':
/home/pi/projects/git/trezor-core/vendor/micropython/py/modbuiltins.c:317: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/modbuiltins.o:/home/pi/projects/git/trezor-core/vendor/micropython/py/modbuiltins.c:245: more undefined references to `nlr_jump' follow
build/unix/vendor/micropython/py/objgetitemiter.o: In function `it_iternext':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objgetitemiter.c:41: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/vendor/micropython/py/objgetitemiter.c:55: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objint.o: In function `mp_obj_new_int_from_float':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objint.c:142: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objset.o: In function `set_remove':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objset.c:379: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objstrunicode.o: In function `str_index_to_ptr':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objstrunicode.c:132: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objtype.o: In function `type_call':
/home/pi/projects/git/trezor-core/vendor/micropython/py/objtype.c:938: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/objtype.o:/home/pi/projects/git/trezor-core/vendor/micropython/py/objtype.c:845: more undefined references to `nlr_jump' follow
build/unix/vendor/micropython/py/runtime_utils.o: In function `mp_call_function_1_protected':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime_utils.c:32: undefined reference to `nlr_push'
build/unix/vendor/micropython/py/runtime_utils.o: In function `mp_call_function_2_protected':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime_utils.c:44: undefined reference to `nlr_push'
build/unix/vendor/micropython/py/runtime.o: In function `mp_load_global':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:174: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_unary_op':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:272: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_call_function_n_kw':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:621: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `checked_fun_call':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:953: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_load_method':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1081: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_load_method_protected':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1092: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1100: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_store_attr':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1119: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_getiter':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1160: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_iternext_allow_raise':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1182: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_iternext':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1203: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1218: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_unpack_sequence':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:857: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_unpack_ex':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:914: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_resume':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1253: undefined reference to `nlr_push'
build/unix/vendor/micropython/py/runtime.o: In function `mp_import_from':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1350: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_parse_compile_execute':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1422: undefined reference to `nlr_push'
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1445: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_raise_msg':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1466: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `m_malloc_fail':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1458: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_binary_op':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:579: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o: In function `mp_raise_OSError':
/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1479: undefined reference to `nlr_jump'
build/unix/vendor/micropython/py/runtime.o:/home/pi/projects/git/trezor-core/vendor/micropython/py/runtime.c:1488: more undefined references to `nlr_jump' follow
build/unix/vendor/micropython/py/vm.o: In function `mp_execute_bytecode':
/home/pi/projects/git/trezor-core/vendor/micropython/py/vm.c:177: undefined reference to `nlr_push'
build/unix/vendor/micropython/ports/unix/unix_mphal.o: In function `sighandler':
unix_mphal.c:(.text.sighandler+0x38): undefined reference to `nlr_jump'
collect2: error: ld returned 1 exit status
`

**Comment by prusnak** [comment]
Micropython UNIX port is not compatible with ARM architecture yet.

**Comment by okipol88** [comment]
> The micropython itself is compilable when first compilig the axtls library.

I was capable of compiling and executing the Micropython on a Raspberry. 
I do not know however to what extent it is usable with Trezor-Core.

Is this not sufficient?

[Compiling Micropython on Raspberry](https://www.raspberrypi.org/forums/viewtopic.php?t=191744)

**Comment by prusnak** [comment]
Feel free to experiment with our code on Raspberry, it should be possible if you made Micropython working there. Please send changes if any are required.

**Comment by okipol88** [comment]
I did compile Micropython on Raspberry Pi 3.
I have no knowledge on the Scons tool.

The output is as is -> the (Exception handling???) nlr_jump/push seems missing or not compilable but on Trezor. I will try to give an update to the extent od which I am capable.

**Comment by prusnak** [comment]
I just pushed an update to the repository (commit https://github.com/trezor/trezor-core/commit/a15eb933e1f0412e283c815fa1a654d16c0bfa26)

Can you check if that helps?

**Comment by okipol88** [comment]
Will give it a go when I will have the Raspberry at hand at home.
Also I should be getting a NanoPi Fire3 -> but guess there should not be a problem there.
Thanks for the update, will keep you posted on the outcome.

**Comment by prusnak** [comment]
OK, please reopen the issue if the commit above didn't help. Thank you!

**Comment by okipol88** [comment]
Hi,
Thank you very much ;) works like a charm ;).

![2018-10-26-213424_1280x1024_scrot](https://user-images.githubusercontent.com/8424432/47588699-4ce90a80-d967-11e8-9169-78218591e783.png)

**Comment by okipol88** [comment]
As a followup I can mention firmware does not build however (with make build_firmware).
I was however most interested in the simulator.

Error for buil_firmware:

```
Traceback (most recent call last):
  File "vendor/micropython/tools/mpy-tool.py", line 594, in <module>
    main()
  File "vendor/micropython/tools/mpy-tool.py", line 582, in main
    raw_codes = [read_mpy(file) for file in args.files]
  File "vendor/micropython/tools/mpy-tool.py", line 447, in read_mpy
    raise Exception('not a valid .mpy file')
Exception: not a valid .mpy file

```

**Comment by prusnak** [comment]
I am afraid cross-compiler (producing .mpy files) won't work on ARM.

**Comment by okipol88** [comment]
Thats fine with me. Happy the simulator is up and running ;).
