### ISSUE TITLE
Inconsistent ResetDevice message in T1 and TT

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#392]
FW: 1.7.1 & 2.0.8
I'm testing "seedless setup".

When i call "ResetDevice" message without flag "strength" it works on T1 (it sets default value 256) on TT it returns "Invalid strength (has to be 128, 192 or 256 bits)"

Thera are also differences in success message:

T1: "Device successfully initialized"
TT: "Initialized"

Additional issue: "no_backup" flag on T1 disappears after device disconnection

**Comment by prusnak** [comment]
Let's set the default in Connect to 256. T1 no_backup issue is a separate one.
