### ISSUE TITLE
investigate and implement OMNI layer

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#399]
and add Tether to supported coins

**Comment by jhoenicke** [comment]
Related: https://test.jochen-hoenicke.de/crypto/omni/ :)

**Comment by prusnak** [comment]
Implemented parsing of OMNI OP_RETURN in 4693c071b44ecb9820ebfa34477fcc095f3fcc05

**Comment by prusnak** [comment]
Not sure we can do anything more for Trezor here :-/

We'd need to have a coin-selection in the wallet, which would pick the UTXOs with OMNIs on them. This is currently a no-go for our web wallet, so most probably only Electrum will be supported for now (or someone will implement a Trezor support for some of the OMNI wallets if there are any).
