### ISSUE TITLE
ui: Word confirmation in seed recovery sometimes miss the touch

### ISSUE THREAD

**Issue by slush0** [trezor/trezor-core#401]
When entering words on display in seed recovery workflow, the top button is often missing touch. I see that the touch even has been registered, because display flickers a bit, but nothing happen. I have to click several times to get touch (and word) accepted.

**Comment by jpochyla** [comment]
Failed to replicate this with recent 2.0.10. Can you confirm the bug is still present?

**Comment by 0x5826** [comment]
solved, thanks!

Jan Pochyla <notifications@github.com>于2019年1月15日 周二下午10:57写道：
