### ISSUE TITLE
Trezor Model T flicker screen after I upgraded v2.0.9

### ISSUE THREAD

**Issue by 0x5826** [trezor/trezor-core#402]
Today I upgraded my trezor T to v2.0.9.
when I touch the screen, Trezor Model T flicker screen and i can't click exactly. no matter i downgrade the version or not, it doesn't work. but in bootloader mode, there is no problem.

I don't think The screen of model T have problems, because it works fine before I upgrade. and some people got the same problem like me.

seem like  #104 
ps:the video is https://www.youtube.com/watch?v=V6oyu-kfD9M

**Comment by matejcik** [comment]
FWIW I was able to reproduce the video perfectly just moments ago, but now I can't anymore :(

So just to note: there is also something to do with the touch panel having problems around screen edges. A workaround for the issue seen on video is moving your thumb a little up.

Flickering when touching elsewhere than the button is also present in lower versions, maybe a little less but it's definitely there.

**Comment by 0x5826** [comment]
I upgraded v2.0.10, I tested it but the issue always happen on macbookpro macOS 10.14.2.
check the video [https://youtu.be/cbt5-aXAhCw](url)
Is it my laptop usb voltage problem or other problem?

**Comment by prusnak** [comment]
It's really weird this happens only on your MacBook, but desktop PC is fine. We'll be tuning sensitivity of the touchscreen in the upcoming release, so this might get fixed too.

**Comment by prusnak** [comment]
@0x5826 we'll handle this in https://github.com/trezor/trezor-core/pull/439
