### ISSUE TITLE
When I enter passphrase on device and confirm it takes too long for screen to disappear  

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-core#433]
When I enter the passphrase and confirm the screen seems to be stuck for 2-3 seconds before it disappears. 
![photo_2018-12-05_16-19-59](https://user-images.githubusercontent.com/31442634/49523277-b7b42c80-f8a9-11e8-8862-db49a4870fc9.jpg)

**Comment by prusnak** [comment]
Fixed in #453
