### ISSUE TITLE
use format_amount for formatting currency values

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#436]
Context: https://github.com/trezor/trezor-core/issues/435

* Cardano will be fixed via https://github.com/trezor/trezor-core/pull/417
* Lisk needs fix: https://github.com/trezor/trezor-core/blob/4c46a055ff5481326bade62af1b6364b5e45acec/src/apps/lisk/layout.py#L54-L55
* Monero needs fix: https://github.com/trezor/trezor-core/blob/4c46a055ff5481326bade62af1b6364b5e45acec/src/apps/monero/layout/common.py#L116-L117
* NEM needs 3 fixes: https://github.com/trezor/trezor-core/blob/4c46a055ff5481326bade62af1b6364b5e45acec/src/apps/nem/transfer/layout.py#L48 and here https://github.com/trezor/trezor-core/blob/4c46a055ff5481326bade62af1b6364b5e45acec/src/apps/nem/transfer/layout.py#L91 and here https://github.com/trezor/trezor-core/blob/4c46a055ff5481326bade62af1b6364b5e45acec/src/apps/nem/transfer/layout.py#L104

**Comment by jpochyla** [comment]
Fixed by e40e3c1fb and 3a408591d
