### ISSUE TITLE
test_apps.monero.bulletproof.py fails after updating trezor-crypto submodule

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#440]
https://travis-ci.org/trezor/trezor-core/builds/469270397

```
class TestMoneroBulletproof
  test_1 ... ok
  test_masks ...Traceback (most recent call last):
  File "test_apps.monero.bulletproof.py", line 440, in <module>
  File "/home/stick/work/trezor/trezor-core/tests/unittest.py", line 220, in main
  File "/home/stick/work/trezor/trezor-core/tests/unittest.py", line 168, in run
  File "/home/stick/work/trezor/trezor-core/tests/unittest.py", line 205, in run_class
  File "/home/stick/work/trezor/trezor-core/tests/unittest.py", line 200, in run_class
  File "test_apps.monero.bulletproof.py", line 283, in test_masks
  File "test_apps.monero.bulletproof.py", line 33, in mask_consistency_check
  File "/home/stick/work/trezor/trezor-core/tests/unittest.py", line 38, in assertNotEqual
  File "../src/trezor/utils.py", line 42, in ensure
AssertionError: bytearray(b'W\xecYu\xab\xffd\\\xbb\xd3!7\xdd*\x8cq\xdbO\xae)\xc8k\xba\xe5tG\x86a\xe0\xe3\x12\r') not expected to be equal bytearray(b'W\xecYu\xab\xffd\\\xbb\xd3!7\xdd*\x8cq\xdbO\xae)\xc8k\xba\xe5tG\x86a\xe0\xe3\x12\r')
```

It is related to https://github.com/trezor/trezor-crypto/commit/c5227fdb969520de41664bfa4b66e74e718d72c4 (the error disappears when I revert this commit in `vendor/trezor-crypto`).

**Comment by prusnak** [comment]
Straightforward fix would be to use RNG for trezor-core emulator using `srand`/`rand` from glibc, but I am hesitant to do this unless we fully understand the problem and decide that's the correct thing to do.

**Comment by tsusanka** [comment]
@ph4r05 we have changed the trezor-crypto RNG not to be intialized with time, but with seed = 0 and we use [LCG](https://en.wikipedia.org/wiki/Linear_congruential_generator), see https://github.com/trezor/trezor-crypto/commit/c5227fdb969520de41664bfa4b66e74e718d72c4 . Is the fix for Monero tests straightforward? We don't mind doing it ourselves, just in case you have some feedback on this..

**Comment by prusnak** [comment]
I would vote against using Mersenne Twister, we need it to be simple (because we are reimplementing it in pure Python too). Let's just pick LCG with longer period, which outputs 32 usable bits, so we can drop random8() completely and use LCG directly in random32().

**Comment by tsusanka** [comment]
This is exactly what I wanted to write. I don't think we are calling random8 anywhere anyway, so this is a reasonable option. I'll do it

**Comment by ph4r05** [comment]
OK no problem, your call. 

Recently I addressed the same problem, we were optimizing python prototype in Python porting to C++ and NTL. We verified it by using MT19937 with the same seed.

Python version of MT: https://repl.it/@DusanKlinec/MersenneTwisterPython
C++ is trivial: https://repl.it/@DusanKlinec/MersenneTwisterCpp

**Comment by tsusanka** [comment]
I think Python uses Mersenne Twister anyway, so we could do it. But I still think option 1 is quicker and easier

**Comment by tsusanka** [comment]
I can confirm this fix (see [PR](https://github.com/trezor/trezor-crypto/pull/191)) fixes this issue.
