### ISSUE TITLE
Enable firmware updates without need for access to mnemonic seed

### ISSUE THREAD

**Issue by bmiller59** [trezor/trezor-core#444]
I have my mnemonic seed stored in a secure off-site location. It is intentionally a big hassle, for security reasons, to go and retrieve this seed.

I would like to be able to update my firmware without having access to my seed. Requiring me to have access to the seed creates a security catch-22.
* If I do not upgrade the firmware, I do not benefit from security upgrades
* If I do upgrade the firmware, I must have access to the seed, which opens me to having the seed stolen. It also wastes a lot of my time and is very inconvenient.

Thank you for addressing this security flaw in the firmware upgrade process.

**Comment by prusnak** [comment]
You can upgrade without the seed if you take full responsibility.

**Comment by bmiller59** [comment]
Good to know. 

So to summarize:
- Upgrade CAN proceed without need for access to seed despite the warning to have seed available during the process
- After upgrade, my wallet and keys will be intact if all went as expected
- If anything went wrong and I need to wipe/restore my Trezor from scratch I could then retrieve my seed and re-set up my Trezor fresh with it at that point

That is what you are saying? Thank you for clarifying.

**Comment by prusnak** [comment]
1) yes, it can
2) yes, in 99.99% cases; the warning is there for the rest 0.01% cases when the update can brick your device (i.e. USB cable fault, etc).
3) yes
