### ISSUE TITLE
Trezor One - 1.7.1 Issues - Hangs on Second Use - Can't Upgrade Firmware

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-core#446]
I am getting issues with Trezor 1.7.1 firmware. I am able to connect to the device once and read/write, but the second time it fails. This bug occurs in LibUsbDotNet, WinUsbNet, and Trezor.Net. However, I can't tell if this is a problem with the latest firmware because I can't upgrade. I am trying to use the beta wallet to upgrade the firmware, but when I do, I get this problem:

![image](https://user-images.githubusercontent.com/16697547/50552856-8d129380-0cf0-11e9-8e68-6b99cea55627.png)

I have tried wiping the device, but I cannot upgrade to the latest firmware with the beta wallet.

**Comment by MelbourneDeveloper** [comment]
To recreate the issue I am having with firmware 1.7.1 you can see the problem with LibUsbDotNet. The problem is NOT specific to LibUsb. This problem is occurring with any WinUSB API calls. But, it is a problem with any LibUsb based code on Windows. This may be fixed in the later version of 1.7.x

- Clone this repo: https://github.com/MelbourneDeveloper/LibUsbDotNet.git
- Open the solution in Visual Studio 2017
- Open the solution LibUsbDotNet.sln
- Plug in a 1.7.1 Trezor One
- Set the Read.Write example as the startup project
- Run the sample
- It will work the first time around
- It will hang on the Write method the second time around

Now repeat the process but use a 1.6.x device, and change VendorId to 0x534C. It works fine again and again.

**Comment by prusnak** [comment]
This was fixed in firmware 1.7.3. Please upgrade. There is a hack how to workaround this issue for lower firmware versions, so you can perform the upgrade: https://wiki.trezor.io/Device_not_recognized_in_bootloader_mode
