### ISSUE TITLE
Enabling coin / UTXO management features

### ISSUE THREAD

**Issue by Enegnei** [trezor/trezor-core#449]
Two years ago, Alena was asked if Trezor would enable the ability to spend from individual bitcoin addresses instead of all addresses within each 'Account.' I believe she said that coin / UTXO management stuff was considered "an advanced feature" and not on the roadmap. Is that still the case?

Currently, since users are limited to 10 'Accounts' (+ any leftover legacy 'Accounts'), this would mean that a user needs generate a new wallet for each set of 10 addresses they want to keep separated.

**Comment by prusnak** [comment]
Yes, it is still the case. You can do this in a wallet aimed for geeks such as Electrum.
