### ISSUE TITLE
utilization of random32() from rand.c 

### ISSUE THREAD

**Issue by ca333** [trezor/trezor-core#454]
While rebuilding trezor-core for Komodo integration tests i noticed the warning ref. `rand.c`:

> NOT SUITABLE FOR PRODUCTION USE! Replace random8() and random32() functions with your own secure code.

Now random32() is indeed defined in there. Do you suggest using a diff. lib/func for this?

**Comment by prusnak** [comment]
This is expected if you build the emulator.
