### ISSUE TITLE
u2f counter not set after recovery, preventing some cases of u2f

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-core#457]
u2f counter is not set after discovery, even when it's sent in  RecoveryDevice message

To reproduce:
- do a recovery device on webwallet
- go to https://demo.yubico.com/u2f?tab=login and do the example login, counter will be 1, even when the u2f_counter in the RecoveryDevice is the current timestamp

This prevents use of trezor as u2f after recovery on websites that check the counter (such as Google)

**Comment by karel-3d** [comment]
yep it seems the u2f counter is ignored here and never saved to storage

https://github.com/trezor/trezor-core/blob/0ff7034e3770e4773e9e981fa485904e51bba5cf/src/apps/management/recovery_device.py#L59

**Comment by prusnak** [comment]
Correct, trezor-mcu does set U2F counter via Recovery message (https://github.com/trezor/trezor-mcu/blob/7dce7bd92d65726e08e0311f9821f6cc966b44a1/firmware/recovery.c#L478)

**Comment by jpochyla** [comment]
Fixed in 2d70d5d
