### ISSUE TITLE
Trezor One: serious issues with latest firmware (1.7.3)

### ISSUE THREAD

**Issue by viaj3ro** [trezor/trezor-core#460]
I have 3 Trezor One. Unfortunately I've installed the latest firmware on two of them. Now every single time I plug them in, I can't disconnect them anymore. The wallet will just freeze at: 

>Disconnect your Trezor now - Trezor Wallet will forget your device right after you disconnect it.

When I try to reconnect after, wallet.trezor.io asks me every time to install the Trezor Bridge which is already installed. Only after installing it again, I get access. But only until I try to disconnect. 

The third Trezor wich is at least one firmware version behind (I last updated around Christmas) is unaffected.

I'm on a fully updated Win7Pro SP1

**Comment by matejcik** [comment]
This is not the right place to report this kind of issue: `trezor-core` is code for TT, not One, and your issue seems more related to the wallet software, or possibly bridge.

Please go through https://trezor.io/support/ where they will help triage the problem and make bug reports if appropriate.
