### ISSUE TITLE
Stellar: source account does not match address_n

### ISSUE THREAD

**Issue by s-a-y** [trezor/trezor-core#462]
Hey,
Can we remove this check
https://github.com/trezor/trezor-core/blob/c1bf6abbeea0a83a31dfacdc76ff7598b0e0a025/src/apps/stellar/sign_tx.py#L51

Use cases:
1) Using channel accounts
https://www.stellar.org/developers/guides/channels.html
Source account of transaction is different from the source of operation (and trezor is source of operation). I still need to be able to sign such transaction

2) Multi-signature
https://www.stellar.org/developers/guides/concepts/multi-sig.html
Imagine account thresholds are set to 2,
I have 3 trezor accounts, each trezor account has weight 1
It means that I can sign with 1 trezor (when source account matches trezor account), but I cannot sign with the other one.

This check can also be upgraded to verify that trezor address is present in transaction source or one of operation sources or is signatory for one of those source accounts. But this is slightly more complicated

**Comment by prusnak** [comment]
@zulucrypto any comments on this? I guess we have the same check in trezor-mcu (Trezor One)

**Comment by tsusanka** [comment]
I think we can do this. The user should confirm the source account however. So, how about the check stays, but when it fails it will not be an error, but we rather inform the user that the source account is equal to XY and does not conform to Trezor's. @s-a-y what do you think?

**Comment by s-a-y** [comment]
works for me, maybe worth emphasizing as well, that source account is paying transaction fee, not necessarily trezor user.

**Comment by tsusanka** [comment]
I see. Maybe in that case (source account != our account) we can just modify the message from `Pay x fee` to `Set x fee` or something like that.

**Comment by tsusanka** [comment]
> I think we can do this. The user should confirm the source account however.

I forgot we are already prompting the user at the beginning:

![screenshot from 2019-01-17 16-40-17](https://user-images.githubusercontent.com/1835345/51329979-e27fcc00-1a76-11e9-8fbd-e2f267263861.png)

Do you think this is enough or should we stress out that the source address is different that the user's?

**Comment by tsusanka** [comment]
I think the best solution is to modify this screen to show "Initialize signing with your account" in case it mateches and show the above if not.

**Comment by tsusanka** [comment]
Implemented in https://github.com/trezor/trezor-core/commit/ea775c2750ef1a2221166de484c79e72e873e1a3 . I've left the fee sentence as it was for the time being.
