### ISSUE TITLE
Trezor TT (2.0.11): EthereumSignTx data safety check error

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-core#474]
When i sign ethereum transaction with some dummy data (0x00) i see on display (data are not smart-contract, they are just some data):
![screenshot 2019-02-13 at 14 31 58](https://user-images.githubusercontent.com/3435913/52715653-41b0fd80-2f9d-11e9-934d-f1756598c928.png)

But when i skip data field (data = undefined) it fails:

error:"Safety check failed"
code:"Failure_DataError"

**Comment by prusnak** [comment]
Please show the contents of the `EthereumSignTx` message.

**Comment by szymonlesisz** [comment]
case 1 (screenshot):
{
    "to": "0x7314e0f1c0e28474bdb6be3e2c3e0453255188f8",
    "value": "0xf4240",
    "data": "0x01",
    "chainId": 1,
    "nonce": "0x0",
    "gasLimit": "0x5208",
    "gasPrice": "0xbebc200"
}

case 2 (failure)

{
    "to": "0x7314e0f1c0e28474bdb6be3e2c3e0453255188f8",
    "value": "0xf4240",
    "chainId": 1,
    "nonce": "0x0",
    "gasLimit": "0x5208",
    "gasPrice": "0xbebc200"
}

**Comment by szymonlesisz** [comment]
solved.
it turns out that type "to" in "EthereumSignTx" message was also changed from "bytes" to "string" in 2.0.11
