### ISSUE TITLE
Display not properly refreshing in 2.1.0

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-core#476]
Display not properly refreshing.
See attached video 
https://photos.app.goo.gl/AQjwCybL465GRggC8

Content of display is deleted when you swipe during confirmation of your action.
It happens during on-boarding and during name change. So it probable happens duringany confirmation.

FW version: 2.1.0
it's not happening with FW version 2.0.10

**Comment by jpochyla** [comment]
Fixed in 4709af1
