### ISSUE TITLE
Display gets dimmed during unlock in 2.1.0

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-core#477]
In firmware version 2.1.0 /there was no please wait in previous version/
display gets dimmed during unlock, or PIN changes and so on.
After this operation it lights up again.

**Comment by jpochyla** [comment]
I don't understand the problem. We slide into the loader animation and then slide out of it, no?

**Comment by jpochyla** [comment]
Fixed in 86bec3b, thanks!
