### ISSUE TITLE
debug mode randomly enabled?

### ISSUE THREAD

**Issue by th3geek** [trezor/trezor-core#482]
Hi all,

I'm freaking out a little bit... When I do a `trezorctl list` its reporting that my trezor is "Debuglink enabled", which I figured was some sort of stock thing (since I've never knowingly enabled it) but after doing a search I see that its possible to read the trezors memory and even extract the private keys!  yikes!  How can this be an allowed function with a security device like trezor! There is also very little information about how to disable and enable debuglink and most of the information about it is sandwiched deep between lines of code and discussions from developers.

Please help!  I'm worried someone got access to my device and was able to enable debug to get at my keys. Once I realized the seriousness of it, I'm a bit hesitant to plug it into my computer.  I hope in the future you consider building a developers edition or something so the debug isn't available off the USB.

Thank for any help!

**Comment by matejcik** [comment]
this is a problem with your old version of `trezorctl`, not with Trezor.

see my reply on Reddit: https://www.reddit.com/r/TREZOR/comments/atrnts/trezor_debuglink_enabled/eh3s1c0/

**Comment by th3geek** [comment]
Thank you so much for your reply on reddit.  Very Helpful. But just FYI, I am using trezorctl version 0.11.1 with a modelT
