### ISSUE TITLE
Investigate the new Dash TX format

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#484]
It seems that Dash did a hard fork which introduces a new TX format. The old TX format still works, but there might be some trouble while spending the new format because Dash doesn't use BIP-143 and needs to stream prev-txs.

**Comment by gladcow** [comment]
I have new Dash txes support for trezor,  I am creating unit tests now and am prepareing PRs in trezor-core, trezor-common, trezor-mcu. I can create PRs right now as [WIP] (work in progress) if it is better.

**Comment by prusnak** [comment]
Please send PRs once you are ready. Start with trezor-common, then with -core, and finally -mcu.

**Comment by gladcow** [comment]
I've added PR to trezor-common https://github.com/trezor/trezor-common/pull/283

**Comment by tsusanka** [comment]
We've decided not to support DIP2 transactions currently. We have limited scope of what we can add to firmware (and mainly maintain). I hope that's understandable.
