### ISSUE TITLE
U2F authentization and passphrase screens overlap

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-core#485]
moved from https://github.com/satoshilabs/trezor-qa/issues/77

TT with passphrase enabled, fw: 2.0.10, 2.1.0
dropbox or github with U2F authentization enabled

Steps to reproduce:
1. go to an arbitrary site with U2F authentization (dropbox, github), log in and wait for a security key prompt
2. go to wallet.trezor.io and wait for the passphrase prompt
3. tap the upper part of the TT screen (not the buttons)

The screens now overlap. Tapping the Host button displays the passphrase entry info screen correctly, tapping the Device button displays a passphrase entry screen still with some elements from the security key prompt screen.

![photo_2019-02-28_12-20-44](https://user-images.githubusercontent.com/10185314/53580310-99de2700-3b7b-11e9-89eb-c3dba42f6071.jpg)
![photo_2019-02-28_18-22-55](https://user-images.githubusercontent.com/10185314/53585322-e9295500-3b85-11e9-9457-b33830ba4fcb.jpg)
![photo_2019-02-28_18-35-49](https://user-images.githubusercontent.com/10185314/53586082-b08a7b00-3b87-11e9-9d9a-592831cf43a4.jpg)

**Comment by prusnak** [comment]
Fixed in 3f0e3a334e03f49ff819d14cbbec00194c586c27
