### ISSUE TITLE
Firmware 2.1.0 is not tagged

### ISSUE THREAD

**Issue by yura-pakhuchiy** [trezor/trezor-core#488]
Makes verification by rebuilding and comparing fingerprint not possible by users.
Also recent [change of fingerprint](https://github.com/trezor/webwallet-data/commit/ff75d534f0ba675ff3a51988de57ea9095dc8482) in webwallet-data repo looks a bit suspicious.

**Comment by prusnak** [comment]
It's tagged in the private branch, which will be merged into master today (after the official release).

The firmware has not been officially released yet. We found a bug and fix caused the fingerprint change.
