### ISSUE TITLE
Cardano sign/verify does not have tests

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#492]
It looks like Cardano does not have tests for sign/verify functions. @ddeath do you actaully use this functionality in Adalite? Or anywhere else?

**Comment by refi93** [comment]
@tsusanka we don't use in AdaLite signing/verifying of arbitrary messages, only transactions

**Comment by tsusanka** [comment]
@prusnak let's remove it? I think it's the same case as before for other coins. The sign/verify functions were added mostly because other coins had it. But if it has no direct usage for the coin.. We can return it easily if needed

**Comment by tsusanka** [comment]
ACKed by stick
