### ISSUE TITLE
Passphrase dialog should cleanup the UI

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-core#493]
After I enter the passphrase, the Passphrase dialog stays on the device until the next message is received.

If no other message comes, this is very confusing.

**Comment by tsusanka** [comment]
@prusnak is this still an issue? I'm having troubles reproducing it

![Peek 2019-03-29 15-33](https://user-images.githubusercontent.com/1835345/55239975-170ec180-5238-11e9-81c9-517ff05baac1.gif)

**Comment by prusnak** [comment]
Reproduce it in the web wallet, where you enter wrong passphrase into a remembered device (so webwallet will compare the hash and stop).

**Comment by tsusanka** [comment]
Confirmed.

![Peek 2019-03-29 16-31](https://user-images.githubusercontent.com/1835345/55243771-298cf900-5240-11e9-9994-f84cd6368a8c.gif)

**Comment by tsusanka** [comment]
This is most likely a wallet issue, moved to https://github.com/satoshilabs/mytrezor/issues/703
