### ISSUE TITLE
JS lib to verify SegWit P2SH addresses

### ISSUE THREAD

**Issue by paulinasd** [trezor/trezor-core#498]
Is there a JavaScript lib in Trezor's codebase that would allow verifying SegWit P2SH addresses from Node.js app without having to connect to Trezor's device? (similar to https://github.com/bitcoinjs/bitcoinjs-message)

**Comment by jpochyla** [comment]
This is a repository for Trezor firmware, but I beliave we don't have any such library in the JS stack, sorry.
