### ISSUE TITLE
Safety check failed error after upgrading to 1.8.0

### ISSUE THREAD

**Issue by rodrigopavezi** [trezor/trezor-core#501]
Hi There,
I have upgrade Trezor firmware to 1.8.0 but then now I am getting the following error.

[trezor-link] Calling BridgeTransport.call( 382 EthereumSignTx { address_n: [ 2147483692, 2147483708, 2147483648, 0, 0 ],
    nonce: '05',
    gas_price: '0165a0bc00',
    gas_limit: '5208',
    to: '23d233933c86f93b74705cf0d236b39f474249f8',
    value: '09184e72a000',
    chain_id: 3 } false )

Error:

[trezor-link] Done BridgeTransport.call, result  { type: 'Failure',
    message:
     { code: 'Failure_DataError', message: 'Safety check failed' } }

Does anyone know what could be happening?

Cheers

**Comment by prusnak** [comment]
Contact our support at trezor.io/troubleshooter
