### ISSUE TITLE
Trezor T freezing during dry run recovery

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-core#509]
Start dry run recovery.
Select first letter.
Swipe to different letter.
Display will flicker.
Swipe longer and device freezes till it's reconnected.
No error in log /except disconnect info when disconnected/

Linux Mint,Bridge 2.0.26, Chrome

I was able to reproduce it.

**Comment by prusnak** [comment]
Firmware version?

**Comment by bosomt** [comment]
2.1.0
i will try to reproduce it in 2.0.10

**Comment by bosomt** [comment]
nope just 2.1.0 with PIN protection

**Comment by tsusanka** [comment]
Could by solved by #162

**Comment by tsusanka** [comment]
I was unable to reproduce this on current master, so it may indeed be solved by #162. I'll give this to @bosomt to try it out.

**Comment by bosomt** [comment]
i was able to reproduce it under 15sec :)
And yes it's most likely caused by rotate screen feature

**Comment by tsusanka** [comment]
This was a misunderstanding. @bosomt was still trying 2.1.0. I've prepared a device with master code on it and will give it to testing.

**Comment by tsusanka** [comment]
Unfortunately we were able to reproduce this with Seb :(

**Comment by tsusanka** [comment]
Although we were able to reproduce this at the end, we had to swipe all the over the screen to get it frozen. I'm pretty sure we've improved it by #162. There's still an an edge case when it freezes, but I believe we can omit that for the time being and fix later if necessary.

----

So I'm assinging to Boso, so he can test if it really improved.

**Comment by tsusanka** [comment]
Closing now, it is partially fixed and partially replaced by https://github.com/trezor/trezor-firmware/issues/22
