### ISSUE TITLE
Stellarport fails singing some dummy transaction

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#511]
From email:

Looks like there is some issue with the new firmware signing some transactions. Is there any way you could test it out at stellarport.io ? You can try going to Wallet > Profile and setting a nickname. In order to set a nickname, it asks you to sign a dummy transaction and gets stuck with an error of "Illegal Buffer".

---------

I'm not 100% sure this is a firmware issue, this might caused by incorrect use of Connect. Will investigate.

**Comment by tsusanka** [comment]
I've looked into this briefly and I don't think this is a firmware issue. Stellarport says "Illegal value for Message.Field .StellarManageDataOp.key of type string: object (not a string)". I believe we need to investigate what Stellarport is sending into Connect because, the operation message doesn't make it into Trezor (StellarManageDataOp).

**Comment by tsusanka** [comment]
Closing for no response, will open again if that changes.

**Comment by istrau2** [comment]
@tsusanka Sorry for the delay,

We have fixed the

> "Illegal value for Message.Field .StellarManageDataOp.key of type string: object (not a string)"
which seems to have exposed another issue in connect/firmware. It seems that something is choking when a base64 encoded string is passed as the value in the manage data operation:
https://github.com/trezor/connect/blob/develop/src/js/types/stellar.js#L105

You can reproduce by going to Wallet > Profile and setting a nickname. Doing so now produces the following error which seems to be generated by connect or firmware:

> Illegal str: Contains non-hex characters

Thanks

**Comment by prusnak** [comment]
@istrau2 Show us the message causing the error. My guess is, surprise, surprise, that one field contains non-hex characters, despite it should not.

**Comment by istrau2** [comment]
@prusnak The transaction looks like:

`{"source":"GABWHTAVRYF2MCNDR5YC5SC3JTZQBGDZ3HKI4QAREV5533VU43W4HJUX","fee":100,"sequence":"0","timeBounds":{"minTime":"1555104914","maxTime":"1555105214"},"operations":[{"source":"GDZPDP7JQMR66FOUN7EOLXRYOICHFDIBEVYLL6ISXA7P2HTNIP775K7B","type":"manageData","name":"Stellarport auth","value":"rflvVyDLDyNg6SiuxXJ87SG57+SsFINDKOt1nty2w3uXwVE20Jt7wwnAz6eLUWBs8xMIsBthn4jRn+2aec4jog=="}],"memo":{"type":0}}`

Are you saying that data values are not allowed to be base64 encoded? Why do you say that?

Check out this SEP: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#response notice that the data value there explicitly needs to be base64 encoded.

Perhaps I am misunderstanding something?

**Comment by prusnak** [comment]
@istrau2 Show us the message you are sending to Connect, not the internal representation of the message.

Also this seems like a Connect issue - moving to the Connect repo.
