### ISSUE TITLE
Keychain.derive and path validations

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-core#519]
Currently, we first call `paths.validate_path` and prompt the user in case it is a non-standard path. If so and the user agrees it may happen that the Keychain throws `failure: Forbidden key path` if it is outside the app's namespace, which is quite unfriendly.

Do we want to deal with this? Maybe just swap those two operations?

---

You can reproduce this using `trezorctl lisk_get_address -n "43"`. [GIF](https://user-images.githubusercontent.com/1835345/55010263-32818e80-4fe4-11e9-81d3-feebf6a569ad.gif)

**Comment by tsusanka** [comment]
@jpochyla any opinions on this?

**Comment by jpochyla** [comment]
We might somehow pass the keychain into `validate_path` and throw exception there?
