### ISSUE TITLE
Trezor actions are slow

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-core#521]
TT (2.1.0)

You can reproduce this issue in wallet (https://beta-wallet.trezor.io/next/#/) for example sign-verify section. 

* Authenticating device takes like 2 or 3 seconds (was instantly before firmware update)
* Signing message in wallet now takes two more seconds

During these actions I can see loader on trezor screen.
Basically every Trezor action is slower than it was before update.

**Comment by tsusanka** [comment]
This is really weird because I'm not able to reproduce this with the same bootloader and same fw version.

But @vladimirvolek's device takes longer on my computer as well..

We both have PIN and passphrase enabled.

**Comment by tsusanka** [comment]
Have you tried reuploading the firmware? That means wiping and installing the fw again

**Comment by vladimirvolek** [comment]
It works great after reuploading the same firmware for the third time :))
