### ISSUE TITLE
Treezor model T device shows a completely white screen and doesn't start anymore

### ISSUE THREAD

**Issue by moshemalawach** [trezor/trezor-core#522]
For no reason the device doesn't start anymore when plugged in and displays a fully white screen.

No connection is detected on dmesg either when plugged in.

Any idea of the reason?

**Comment by tsusanka** [comment]
Could you provide a firmware version and what OS are you using?

**Comment by tsusanka** [comment]
I believe this is a faulty device. Please contact our support using this form: https://satoshilabs.kayako.com/conversation/new/9

**Comment by tsusanka** [comment]
Not much we can do on the firmware side here.
