### ISSUE TITLE
Protection of passphrase against keylogging and screenshot ?

### ISSUE THREAD

**Issue by prodnet** [trezor/trezor-core#548]
I noticed that there is no protection when entering passphrase in Trezor.io.
It would be great if you could implement a Anti-Keylogger secure Virtual Keyboard, such as Oxynger KeyShield.

Oxynger KeyShield is a secure, anti-screenshot and free virtual keyboard to protect passwords and other sensitive information from malicious programs and hacking. Oxynger KeyShield protects its keystrokes from keystroke logging, screen logging, mouse logging, clipboard logging and shoulder surfing.
Link: https://www.oxynger.com/

**Comment by prusnak** [comment]
You can enter passphrase directly on Model T keyboard.

**Comment by prodnet** [comment]
And for the other customers who bought Trezor One, what solution do you propose?

**Comment by prusnak** [comment]
Buy Model T or use Virtual Keyboard.

**Comment by prodnet** [comment]
Thank you for your reply.
I have one last question:
After fixing the vulnerabilities from firmware version 1.8, a attacker with the necessary technology and physically acces on to the device, can it extract the private keys or the seed?
