### ISSUE TITLE
Trezor T firmware buggy from upper case bech32 addresses

### ISSUE THREAD

**Issue by Perlover** [trezor/trezor-core#554]
Hi,

If to enter in the "Send" Tab at site [wallet.trezor.io](https://wallet.trezor.io) the upper-case bech32 address and to try to sign transaction i got always the "Firmware error" at site and i see circle progress bar 25% only in Trezor T screen. The upper-case Bech32 addresses are valid and they to be used in QR codes for optimization (for example the BLW wallet shows this format through QR code and i use scan address camera). If i change a bech32 address to lower case variant and sign transaction again the screen of Trezor T to be reseted and i can sign transaction successfully.

I submited a ticket to support about one month ago but i don't see any results. The bug exists...

**Comment by Perlover** [comment]
Hi!

Any news? It's annoying problem. The bech32 addresses in upper case - it's recommended case for QR code. But your Trezor T has "firmware error" when spending to bech32 upper case address. I checked now in Elecutrum - same problem. It's not problem wallet.trezor.io for example. It's firmware bug.

**Comment by prusnak** [comment]
Firmware expects lower case addresses. The software wallet should convert the letters to lower case before sending it to the device. 

Thus this is a bug in Electrum: http://github.com/spesmilo/electrum

**Comment by Perlover** [comment]
What about wallet.trezor.io (it's your project and there is same problem)?
And bech32 in upper case is valid address. I think the Trezor should understand valid address. What do you think? I think it is more correct to implement it at the firmware level - it is easier to do it there than to fix it in all the programs that work with Trezor.

**Comment by prusnak** [comment]
It introduces unnecessary complexity into the firmware, that's why I want to do it in the software wallet.
