### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by dominik-selmeci** [trezor/trezor-core#77]
Hi, 
I'm learning how to work with the emulator. I used [this manual](https://github.com/trezor/trezor-core/blob/master/docs/build.md#debianubuntu). The build was without errors. When I access emu.sh through terminal id outputs:

> Traceback (most recent call last):
>   File "main.py", line 112, in <module>
> MemoryError: memory allocation failed, allocating 136 bytes

My system:

> Kubuntu 17.10 64bit (plasma)
> Python 2.7.14 (pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6) )
> gcc 7.2.0
> Kernel 4.13.0-16-generic

I also tried run as sudo user. Outputs the same result.

**Comment by mcudev** [comment]
Same happens for me. If you comment lines 112, 121,110, and 119 in `trezor-core/src/main.py`, you'll at least get something to show up. It'll fail for another reason after that. This isn't a fix, but if you want to get rolling to start working on a fix, this'll help you to at least get something to show in the emulator.

**Comment by prusnak** [comment]
Try again after pulling the master, Dominik. It should work.

**Comment by dominik-selmeci** [comment]
It works! That little window is so satisfying :D.

Thanks for the help.
