### ISSUE TITLE
docs: info on display for dev kit

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#8]
I want to update my dev kit to support TREZOR 2 development (https://mcudev.github.io/trezor-dev-kit/index.html).

I need a display.

It looks like the basic requirements are:

- 240x240 pixel
- TFT LCD 18-bit color screen
- ILI9341V or ST7789V driver
- I2C capacitive touch

Do you have any recommendations on a module to use (preferably on a breakout board with headers)?

I see some 240x320 modules, but not 240x240. Is 240x320 what is actually being used?

For example, this looks close to spec: https://www.adafruit.com/product/2090

**Comment by prusnak** [comment]
Our display is indeed 240x240, but it uses 240x320 pixel buffer internally. Also we currently use ST7789V as the driver. Data bus is 8-bit parallel.

Your selection is fine, though. ILI9341V driver was our original choice, it's not too different from ST7789V. Also nice that your choice has SD-card as TREZOR2 will contain it too.

**Comment by mcudev** [comment]
Thanks for the info!
Indeed, the SD-card being included on that adafruit board is extra convenient.
Quick question, are you getting touch input over the same 8-bit parallel bus? Or, is only screen output over that bus, and touch input comes over I2C?
I quick-skimmed the code and it looked like I2C, but could be wrong.

**Comment by prusnak** [comment]
Correct, touch comes over I2C.

Also, if you think it would be nice to have all this info in one place, I would love to accept a pull request which adds `hardware.md` into `docs/` directory or something similar!

(Btw, I'll close this issue, but feel free to ask more questions, I'll answer twem)

**Comment by mcudev** [comment]
Pull request created https://github.com/trezor/trezor-core/pull/9.

I assumed that doc should be targeted to v2 only.
Do you have any interest in pulling the existing dev kit stuff that I have into one of your repos (https://mcudev.github.io/trezor-dev-kit/index.html)?
I'd be happy to contribute it. It would probably get better use/exposure being in one of your repos.

Another question:
I was looking closer at the adafruit board.
It looks like the microSD is not compatible because that board is setup to use SPI and your code uses a 4-bit data bus for microSD.
Am I reading that correctly?

**Comment by mcudev** [comment]
Nevermind that last question. I'm sure the code is using 4-bit SDIO mode through the SDIO peripheral and not SPI. I think I'll use a cheap separate SDIO breakout and am still looking for a ST7789V display module with cap touch that's easy to use.
