### ISSUE TITLE
firmware: trezorctl get_address passphrase entry not on device

### ISSUE THREAD

**Issue by mcudev** [trezor/trezor-core#82]
Opening this because according to https://preorder.trezor.io/:
"All confidential data, including the PIN, are entered exclusively through the screen."

This meaningfully violates that (I actually care more about the passphrase in this case because the PIN still uses the unpredictable keypad):

```
./trezorctl -t udp get_address -c Bitcoin -n "Bitcoin/0'/0/0"
Use the numeric keypad to describe number positions. The layout is:
    7 8 9
    4 5 6
    1 2 3
Please enter current PIN: 

Passphrase required: 

Confirm your Passphrase:

```

**Comment by prusnak** [comment]
Yes, this is being addressed.

If TREZOR will ask for passphrase on its device it will not send a `PassphraseRequest` message to the computer and computer will not ask for passphrase, so it will be correct.

**Comment by mcudev** [comment]
OK, I was thinking that might be the case in a private branch somewhere. Should I close this, or leave open for later testing?

**Comment by prusnak** [comment]
Keep it opened please.

**Comment by prusnak** [comment]
Since today the device asks whether the passphrase should be entered on the device or from the host. Feel free to check the commit from master. Closing.

**Comment by mcudev** [comment]
I tested this and it seems reasonable. I wasn't expecting the passphrase to persist as long as it did. I don't know that that is necessarily bad, just different. This is what I mean:
With v1 device there is always a passphrase prompt, so you can easily have different passphrases for different coins, like:

$ python2 trezorctl get_address -c Bitcoin -n "Bitcoin/0'/0/0"
Passphrase required: 
Confirm your Passphrase:
$ python2 trezorctl get_address -c Litecoin -n "Litecoin/0'/0/0"
Passphrase required: 
Confirm your Passphrase:

With Model T, you have to unplug and re-plug. If a user is used to the old way and not thinking acutely, they could wind up using addresses under a wrong passphrase. The coins would not be lost, so not a big deal. May be worth a mention in a user guide?

**Comment by prusnak** [comment]
Correct. We plan to modify the behavior (both for T1 and T2) with a "device state".

If you don't provide the `device_state` field in the `Initialize` message, the cached passphrase will be cleaned. At any time you can ask for features and read the `device_state` from the device - this will be essentially a hash of root public key (thus dependent on passphrase).

If you do provide the `device_state` field in the `Initialize` message and it is the same as the current device state in the device - the cached passphrase won't be cleared and thus no passphrase query will appear. If you provide a different device state, the cached passphrase will be removed, too.

This new behavior will fix the issue you see as `trezorctl` will always provide an empty device state.

**Comment by mcudev** [comment]
sounds good
