### ISSUE TITLE
Remove unsupported usage of __attribute__((naked))

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-core#89]
At https://github.com/trezor/trezor-core/blob/5e476b856e64ec787ef1f6849d12023fdd36ee04/embed/firmware/nlrthumb.c#L97 there is a function marked `__attribute__((naked))` containing a mixture of ASM and C code.

To quote https://gcc.gnu.org/onlinedocs/gcc/ARM-Function-Attributes.html#ARM-Function-Attributes

> While using extended asm or a mixture of basic asm and C code may appear to work, they cannot be depended upon to work reliably and are not supported.

**Comment by prusnak** [comment]
This is the upstream issue: https://github.com/micropython/micropython/blob/6b19520a743ddafcdd1881582d4c90a9ea068610/py/nlrthumb.c#L95

Could you please open issue there and link it here?

**Comment by saleemrashid** [comment]
@prusnak https://github.com/micropython/micropython/issues/3491

**Comment by saleemrashid** [comment]
@prusnak https://github.com/micropython/micropython/issues/3484

**Comment by saleemrashid** [comment]
Fixed upstream by https://github.com/micropython/micropython/commit/6a3a742a6c9caaa2be0fd0aac7a5df4ac816081c

**Comment by prusnak** [comment]
Thanks! This will be updated on next upstream (vendor/micropython) stable release.
