### ISSUE TITLE
Include Coin Number in Coins List

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-core#95]
When you initialize the Trezor, it returns are Features message. This message includes a list of valid coins. It would be great if each coin object included the coin number so that when we get addresses we can iterate through this coin list instead of just knowing the number.

Also, the GetAddress message accepts the parameter "coin_name". Why? We are already passing the coin number in as part of the path, so why do we need to send a duplicate value?

**Comment by prusnak** [comment]
You are passing coin number in path only if you use BIP44/49/84, but TREZOR can use any path and some wallets use custom path, that's why it is needed.

For the same reason the Features messages will not contain coin numbers. You should add coin numbers to your application.

**Comment by MelbourneDeveloper** [comment]
@prusnak , I asked @saleemrashid in the chat room, and he said it was easy to add. Notice the main request here is to just add the coin number in the the CoinType proto message. This is just so that if Trezor adds a new coin, my app can use the coin number in the CoinType to try to loop through the addresses. It's so that my app is future proof. I don't need to change my app when you guys add a new coin.

The second part was just a question because I must have missed something.
