### ISSUE TITLE
Get All Coin Information in CoinType

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-core#96]
By default, the My Trezor apps generates BTC addresses at (BIP 49)
m/**49**'/0'/0'/0/_x_

It generates LTC addresses at:
m/**49**'/2'/0'/0/_x_

It generates BCH addresses at
m/**44**'/145'/0'/0/_x_

Would it be possible to include the default BIP number, or possibly even the full default path of the coin? This is related to #95. The reason I ask is because, if a new coin is added, it would be great to get Trezor's default path for the coin. That way, my app can take a good guess about where the coins may be stored and I don't need to create a new version of my app to get the addresses.

**Comment by prusnak** [comment]
If the coin has segwit: false then it is bip44 only.

If it has segwit: true you need to check bip49 path as well.

If it has also bech32 prefix set, then you need to check bip84 path.

No need for extra info added as all info is already stored in segwit and
bech32 fields.

**Comment by MelbourneDeveloper** [comment]
@prusnak thanks! I'm so close on this one. I am now able to mostly get all the information I need from the CoinType list:

        private async Task<GetHoldingsResult> GetTrezorHoldingsAsync(TrezorAccount trezorAccount)
        {
            try
            {
                if (!_TrezorManager.IsConnected)
                {
                    return null;
                }

                await _TrezorManager.InitializeAsync();

                var getCurrencyHoldingTasks = new List<Task<CurrencyHolding>>();

                //Create the tasks for all coins
                foreach (var coinInfo in _TrezorManager.Features.Coins)
                {
                    getCurrencyHoldingTasks.Add(GetTrezorHoldingForSymbol(coinInfo));
                }

                var results = await Task.WhenAll(getCurrencyHoldingTasks);

                return new GetHoldingsResult(results.Where(r => r != null).ToList(), trezorAccount);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

But, I still need to include the Coin Number in my library for coins that require it. That means that if you guys add a coin that requires the coin number, I have to rebuild the app. I couldn't find the Bech32 flag. I see that Bech32 is a part of BIP0173 (https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32) but I'm not sure how I can work out if the coin should use this BIP or not. Is this optional for coins like Bitcoin?

**Comment by MelbourneDeveloper** [comment]
Just so what I'm trying to makes sense, I'll post my code here:

   public class CurrencySymbol
    {
        public enum CoinNumberEnum
        {
            BTC = 0,
            LTC = 2,
            DASH = 5,
            ETH = 60,
            ZEC = 133,
            BCH = 145,
            BTG = 156
        }

        #region Fields
        private string _Name;
        #endregion

        #region Public Properties

        public bool IsEthereum => new List<string> { "ETH", "ETC" }.Contains(Name);

        public string Name
        {
            get => _Name;
            set
            {
                _Name = value.ToUpper().Trim();

                //Use BTC instead of XBT
                if (_Name == "XBT")
                {
                    _Name = BitcoinSymbolName;
                }

                if (_Name == "IOT")
                {
                    _Name = "IOTA";
                }

                if (_Name == "MIOTA")
                {
                    _Name = "IOTA";
                }

                if (_Name == "QTM")
                {
                    _Name = "QTUM";
                }

                if (_Name == "BCC")
                {
                    _Name = BitcoinCashSymbolName;
                }

                if (_Name == "XDG")
                {
                    _Name = "DOGE";
                }
            }
        }

        public uint? CoinNumber
        {
            get
            {
                CoinNumberEnum coinNumber;
                if (Enum.TryParse<CoinNumberEnum>(Name, out coinNumber))
                {
                    return (uint)coinNumber;
                }

                return null;
            }
        }

        #endregion

        #region Public Constants
        public const decimal Satoshi = 100000000;
        public const string BitcoinCashSymbolName = "BCH";
        public const string BitcoinSymbolName = "BTC";
        public const string LitecoinSymbolName = "LTC";
        public const string EthereumClassicSymbolName = "ETC";
        public const string EthereumSymbolName = "ETH";
        public const string RippleSymbolName = "XRP";
        public const string NEOSymbolName = "NEO";
        public const string StellerSymbolName = "XLM";
        public const string DashSymbolName = "DASH";
        public const string BitcoinGoldSymbolName = "BTG";
        public const string ZCashSymbolName = "ZEC";

        public static CurrencySymbol Bitcoin { get; } = new CurrencySymbol(BitcoinSymbolName);
        public static CurrencySymbol Litecoin { get; } = new CurrencySymbol(LitecoinSymbolName);
        public static CurrencySymbol BitcoinCash { get; } = new CurrencySymbol(BitcoinCashSymbolName);
        public static CurrencySymbol Dash { get; } = new CurrencySymbol(DashSymbolName);
        public static CurrencySymbol BitcoinGold { get; } = new CurrencySymbol(BitcoinGoldSymbolName);
        public static CurrencySymbol ZCash { get; } = new CurrencySymbol(ZCashSymbolName);
        public static CurrencySymbol Ethereum { get; } = new CurrencySymbol(EthereumSymbolName);
        public static CurrencySymbol EthereumClassic { get; } = new CurrencySymbol(EthereumClassicSymbolName);
        #endregion

        #region Constructor
        /// <summary>
        /// Don't use this. Only here for serialization
        /// </summary>
        public CurrencySymbol()
        {

        }

        public CurrencySymbol(string name)
        {
            Name = name;
        }
        #endregion

        #region Public Methods
        public override bool Equals(object obj)
        {
            var currencySymbol = obj as CurrencySymbol;
            if (currencySymbol == null)
            {
                return false;
            }

            return string.Equals(currencySymbol.Name, Name);
        }

        public override int GetHashCode()
        {
            var retVal = 0;
            foreach (var character in Name)
            {
                retVal += character;
            }

            return retVal;
        }

        public override string ToString()
        {
            return _Name;
        }

        #endregion
    }

**Comment by MelbourneDeveloper** [comment]
```
        public async Task<string> GetAddressAsync(CurrencySymbol symbol, bool isChange, uint index, bool showDisplay = false)
        {
            if (symbol.CoinNumber == null)
            {
                throw new Exception($"The symbol {symbol} does not have a coin number");
            }

            //ETH and ETC don't appear here so we have to hard code these not to be segwit
            var coinType = Features.Coins.FirstOrDefault(c => c.CoinShortcut.ToLower() == symbol.Name.ToLower());

            var isSegwit = coinType != null && coinType.Segwit;

            var path = GetAddressPath(isSegwit, isChange, index, symbol.CoinNumber.Value);

            if (!symbol.IsEthereum)
            {
                return (await SendMessage<Address, GetAddress>(new GetAddress { ShowDisplay = showDisplay, AddressNs = path, CoinName = GetCoinType(symbol).CoinName, ScriptType = isSegwit ? InputScriptType.Spendp2shwitness : InputScriptType.Spendaddress })).address;
            }
            else
            {
                var ethereumAddress = await SendMessage<EthereumAddress, EthereumGetAddress>(new EthereumGetAddress { ShowDisplay = showDisplay, AddressNs = path });

                var sb = new StringBuilder();
                foreach (byte b in ethereumAddress.Address)
                {
                    sb.Append(b.ToString("X2"));
                }

                string hexString = sb.ToString();

                return $"0X{hexString}";
            }
        }
```

**Comment by MelbourneDeveloper** [comment]
```
                await _TrezorManager.InitializeAsync();

                var results = new List<CurrencyHolding>();

                //Create the tasks for all coins
                foreach (var coinInfo in _TrezorManager.Features.Coins)
                {
                    results.Add(await GetTrezorHoldingForSymbol(coinInfo));
                }

                results.Add(await GetHoldingsForCoin(CurrencySymbol.Ethereum, false));
                results.Add(await GetHoldingsForCoin(CurrencySymbol.EthereumClassic, false));
```

**Comment by MelbourneDeveloper** [comment]
Notice that I have to store the coin number in my code, and whether or not it is Ethereum. Please ETH and ETC don't show up in the Coins list so I have to add those manually.

**Comment by prusnak** [comment]
We decided to use different approach. We don't return coin list at all and one can learn the coin definitions from here:

https://github.com/trezor/trezor-common/tree/master/defs/coins

To see which coins are supported in trezor, look here:

https://github.com/trezor/trezor-common/blob/master/defs/support.json
